/* ============================================================
   dados/herois/_builds.js — itens por herói

   POR QUE ISTO NÃO ENTROU NO CAMPO 'builds' DO BANCO

   O campo hero.builds já existe, e ele é OUTRA COISA: foi feito
   para a fonte prioritária (pvp.mcxssg.net), que publica 出装推荐
   — item por slot COM PORCENTAGEM DE USO E EFEITO NA VITÓRIA.
   Aquilo é contagem: "68,4% compram este item no slot 1, e quem
   compra ganha 0,1 ponto a mais". É auditável.

   Isto aqui não é contagem. É OPINIÃO DE GUIA: alguém escreveu
   "os melhores itens da Jing são estes" e a busca me devolveu um
   resumo dessa frase. Misturar as duas coisas no mesmo campo faria
   a opinião herdar a autoridade da estatística — que é exatamente
   o tipo de mentira silenciosa que este banco recusa. Por isso ela
   mora num campo próprio, com o rótulo colado.

   DOIS NÍVEIS DE CONFIANÇA, E A DIFERENÇA ESTÁ NO CAMPO 'cruzado'

   · cruzado:true, buscas:2 — Jing, Luna e Marco Polo. São os seus
     (e o que você apontou como faltando). Cada um levou DUAS buscas
     independentes, e o resultado está separado em três listas:
     'concordam' (o que as duas deram), 'soUmaBusca' (o que só uma
     deu) e 'divergem' (onde elas se contradizem, com as DUAS
     leituras guardadas). Nada foi escolhido por ser mais bonito.

   · cruzado:false, buscas:1 — os outros 114. Você pediu todos os
     personagens, e 117 heróis × 2 buscas não cabia. Então eles
     entraram com UMA busca cada, num campo 'itens' simples — e o
     app diz "uma busca só" na tela, em vez de deixar parecer que
     têm o mesmo lastro dos três de cima. Uma busca não é
     cruzamento, e chamar de cruzamento seria a mentira que este
     banco inteiro existe para não contar.

   O QUE ISTO NÃO É: ordem de compra. Nenhuma busca devolveu uma
   ordem confiável de slot 1 → slot 6. O campo 'itens' é um
   CONJUNTO. Inventar ordem a partir de lista sem ordem seria
   invenção, então não tem. Onde a busca falou de item inicial,
   ele está em 'inicio', separado.

   NOMES QUE NÃO BATEM com o catálogo (Daybreaker × Daybreaker's
   Virtue, Frostscar's Grip × Frostscar's Embrace) NÃO são
   "corrigidos" por semelhança: fica o que a busca deu.

   ONDE O RESUMO SE ATRAPALHOU, ESTÁ ESCRITO. Sete heróis têm campo
   'nota' com o problema: busca que listou nome de arcana entre os
   itens (Zhao Yun, Wukong), que devolveu rota de habilidade no
   lugar de build (Augran), que deu build de defesa para maga
   (Wang Zhaojun), ou nome ambíguo entre dois heróis da sua lista
   (Wukong × Sun Wukong).
   ============================================================ */
'use strict';
(function (U) {

  /* ============================================================
     NOME DAS ARCANAS EM PORTUGUÊS
     Mesma regra dos itens: 'br' é nome visto em fonte brasileira,
     'eu' é tradução minha e o jogo pode chamar de outra coisa. O
     nome em inglês nunca é apagado — ele é a chave das builds.
     ============================================================ */
  U.HE.ARCANA_PT = {
    'Red Moon':     ['Lua Vermelha', 'br'],
    'Avarice':      ['Avareza', 'br'],
    'Hunter':       ['Caça', 'br'],
    'Eagle Eye':    ['Olho de Águia', 'br'],
    'Fate':         ['Destino', 'br'],
    "Mind's Eye":   ['Terceiro Olho', 'br'],
    'Cataclysm':    ['Cataclismo', 'eu'],
    'Compassion':   ['Compaixão', 'eu'],
    'Concealment':  ['Ocultação', 'eu'],
    'Conflict':     ['Conflito', 'eu'],
    'Dominator':    ['Dominador', 'eu'],
    'Harmony':      ['Harmonia', 'eu'],
    'Longevity':    ['Longevidade', 'eu'],
    'Mutation':     ['Mutação', 'eu'],
    'Nightmare':    ['Pesadelo', 'eu'],
    'Reaver':       ['Saqueador', 'eu'],
    'Reincarnation':['Reencarnação', 'eu'],
    'Reverberation':['Reverberação', 'eu'],
    'Saint':        ['Santo', 'eu'],
    'Tribute':      ['Tributo', 'eu'],
    'Vacuity':      ['Vacuidade', 'eu'],
    'Beast Scar':   ['Cicatriz da Fera', 'eu'],
  };

  U.HE.BUILDS = {
    fonte: 'busca_web',
    fonteNome: 'busca na web (resumo de trechos, não leitura de página)',
    prioritaria: false,
    conferido: false,
    tipo: 'opiniao_de_guia',
    quando: '2026-09-19',
    aviso: 'Isto é opinião de guia, não estatística de partida. A fonte prioritária (pvp.mcxssg.net) publica item por slot com % de uso e efeito na vitória — e ela continua bloqueada nesta sessão. Quando ela entrar, estes números caem fora e os de lá entram.',
    cobertura: '117 de 117 heróis. Mas só 3 são cruzados em duas buscas (Jing, Luna, Marco Polo) — os outros 114 têm UMA busca cada, e a tela diz isso em cada ficha.',
    cruzados: 3,
    umaBuscaSo: 114,
    semOrdem: 'Nenhuma busca devolveu ordem de compra confiável. As listas abaixo são conjuntos, não sequências.',

    porHeroi: {

      jing: {
        cruzado: true,
        buscas: 2,
        urls: [
          'https://www.sportskeeda.com/esports/best-jing-build-honor-kings-equipment-arcanas-battle-spell-skill-combo',
          'https://hokbuild.com/hero/jing/',
          'https://zathong.com/honor-of-kings-jing/',
          'https://gamingonphone.com/guides/honor-of-kings-jing-guide-gameplay-tips/',
        ],
        alerta: 'As duas buscas concordam nos três itens de dano e brigam nas botas: uma diz Boots of Dexterity, a outra Boots of Resistance. As duas ficam registradas. Note que só um dos itens confirmados (Axe of Torment) existe no seu catálogo — o catálogo vai de A até H, e Master Sword e Siege Breaker ficam depois do H.',
        concordam: [
          { nome: 'Axe of Torment', papel: 'perfuração física', noCatalogo: true },
          { nome: 'Master Sword', papel: 'dano físico', noCatalogo: false,
            nota: 'Não está no seu catálogo: ele cobre de A até H e este item vem depois.' },
          { nome: 'Siege Breaker', papel: 'dano físico', noCatalogo: false,
            nota: 'Não está no seu catálogo: ele cobre de A até H e este item vem depois.' },
        ],
        soUmaBusca: [
          { nome: 'Rapacious Bite', papel: 'primeiro item de selva', noCatalogo: false, busca: 'A',
            nota: 'Só a primeira busca citou, e como PRIMEIRO item do core. Item de selva com esse nome não aparece no seu catálogo (que vai só até o H).' },
          { nome: 'Hunting Knife', papel: 'item inicial de selva', noCatalogo: true, busca: 'B',
            nota: 'Só a segunda busca citou, como item de início. Este existe no seu catálogo, com o preço cortado na captura.' },
        ],
        divergem: [
          {
            oQue: 'qual bota',
            leituraA: 'Botas da Destreza / Boots of Dexterity (velocidade de ataque)',
            leituraB: 'Botas da Resistência / Boots of Resistance (defesa mágica e resistência a controle)',
            porQueNaoEscolhi: 'As duas botas existem no seu catálogo e custam o mesmo (700). A escolha entre elas depende da composição inimiga, e nenhuma das duas buscas disse contra o quê. Escolher uma aqui seria dar cara de dado a um chute meu.',
          },
        ],
        feitico: { nome: 'Smite', confianca: 'alta',
          nota: 'As duas buscas deram o mesmo feitiço de batalha.' },
        arcana: {
          leitura: '10 Mutation · 10 Eagle Eye · 10 Concealment',
          confianca: 'alta',
          nota: 'As duas buscas deram exatamente a mesma trinca.',
          conflitoComSuasCapturas: 'ATENÇÃO: o banco já tem uma arcana da Jing vinda das SUAS capturas do HOK PRO, com as contagens 8/2/5/5/10 e sem nomes. Aquilo é o que você tem; isto é o que o guia recomenda. São coisas diferentes e nenhuma das duas foi apagada para caber a outra.',
        },
      },

      luna: {
        cruzado: true,
        buscas: 2,
        urls: [
          'https://zathong.com/honor-of-kings-luna/',
          'https://hokbuild.com/hero/luna/',
          'https://sportskeeda.com/esports/honor-kings-luna-build-guide-best-equipment-arcanas-battle-spell-skill-combos',
          'https://gaminggblog.com/honor-of-kings-luna-build/',
        ],
        alerta: 'Quatro itens saíram iguais nas duas buscas. O quinto briga: uma diz Runeblade, a outra Savant\'s Wrath. A terceira arcana também briga (Red Moon × Nightmare). Só dois dos itens confirmados estão no seu catálogo — os outros ficam depois do H.',
        concordam: [
          { nome: 'Boots of Resistance', papel: 'botas, resistência a controle', noCatalogo: true },
          { nome: "Augur's Word", papel: 'ataque mágico e defesa', noCatalogo: true,
            nota: 'A segunda busca escreveu "Angur\'s Word". Tratei como erro de digitação da própria fonte, e não como item diferente, porque o resto do texto descreve o mesmo item. Fica registrado que a grafia veio torta de lá.' },
          { nome: 'Insatiable Tome', papel: 'ataque mágico, recarga e roubo de vida mágico', noCatalogo: false,
            nota: 'Não está no seu catálogo: ele cobre de A até H.' },
          { nome: 'Void Staff', papel: 'perfuração mágica', noCatalogo: false,
            nota: 'Não está no seu catálogo: ele cobre de A até H.' },
        ],
        soUmaBusca: [
          { nome: 'Breakthrough Robe', papel: 'vida virando perfuração mágica', noCatalogo: true, busca: 'A',
            nota: 'Só a primeira busca citou. Este existe no seu catálogo, com a passiva encontrada.' },
          { nome: 'Hunting Knife', papel: 'item inicial de selva', noCatalogo: true, busca: 'A',
            nota: 'Só a primeira busca citou, e ela também chama a Luna de selva — o que bate com o feitiço Smite da segunda busca.' },
        ],
        divergem: [
          {
            oQue: 'o item de ataque mágico do meio da build',
            leituraA: 'Lâmina Rúnica de Caça / Runeblade (150 de ataque mágico, 5% de recarga, 7% de velocidade de movimento; sobe quando você ou um aliado mata monstro)',
            leituraB: "Ira do Sábio / Savant's Wrath",
            porQueNaoEscolhi: 'A primeira busca descreveu o item com números; a segunda só deu o nome. Ter mais detalhe não torna uma leitura mais certa que a outra — pode só significar que uma fonte escreve mais. Nenhum dos dois está no seu catálogo para eu conferir pelo preço.',
          },
          {
            oQue: 'a terceira arcana',
            leituraA: '10 Lua Vermelha / Red Moon',
            leituraB: 'Pesadelo / Nightmare',
            porQueNaoEscolhi: 'As duas buscas concordam nas outras duas (Hunter e Mind\'s Eye) e divergem só nesta. Sem uma terceira leitura, é 1 contra 1.',
          },
        ],
        feitico: { nome: 'Smite', confianca: 'media',
          nota: 'Só a segunda busca nomeou o feitiço. A primeira falou de selva sem dizer qual feitiço, o que é compatível mas não é confirmação.' },
        arcana: {
          leitura: 'Hunter · Mind\'s Eye · (a terceira está em disputa — ver divergem)',
          confianca: 'media',
          nota: 'Duas das três confirmadas em duas buscas. A terceira briga.',
        },
      },

      'marco-polo': {
        cruzado: true,
        buscas: 2,
        urls: [
          'https://sportskeeda.com/esports/marco-polo-build-honor-kings-best-equipment-arcanas-battle-spell-skill-combo',
          'https://hokbuild.com/hero/marco-polo/',
          'https://zathong.com/honor-of-kings-marco-polo/',
          'https://www.gamewitted.com/gaming/honor-of-kings-marco-polo-build-items-counters-and-arcanas',
        ],
        alerta: 'Este é o herói com a melhor concordância dos três: quatro itens saíram iguais nas duas buscas. Mas DOIS nomes batem só por aproximação com o seu catálogo — "Daybreaker" × "Daybreaker\'s Virtue" e "Frostscar\'s Grip" × "Frostscar\'s Embrace". Eu NÃO casei os nomes: ficou o que a busca deu, com a diferença anotada.',
        concordam: [
          { nome: 'Boots of Dexterity', papel: 'botas, velocidade de ataque', noCatalogo: true },
          { nome: 'Doomsday', papel: 'dano por vida do alvo', noCatalogo: true },
          { nome: 'Sparkforged Dagger', papel: 'velocidade de ataque e dano mágico no básico', noCatalogo: false,
            nota: 'Não está no seu catálogo: ele cobre de A até H.' },
          { nome: 'Daybreaker', papel: 'ataque, velocidade de ataque, crítico e perfuração', noCatalogo: null,
            nota: 'O seu catálogo tem "Daybreaker\'s Virtue" (2570 de ouro). As buscas escreveram só "Daybreaker". Pode ser o mesmo item com o nome cortado, pode ser outro. Não casei os dois — é por isso que noCatalogo está nulo em vez de true.' },
        ],
        soUmaBusca: [
          { nome: 'Siege Breaker', papel: 'dano físico', noCatalogo: false, busca: 'A' },
          { nome: "Frostscar's Grip", papel: 'dano extra no básico depois de habilidade', noCatalogo: null, busca: 'A',
            nota: 'O seu catálogo tem "Frostscar\'s Embrace" (2060). Mesma ressalva do Daybreaker: nome parecido não é prova de ser o mesmo item.' },
          { nome: 'Thunderclap Brand', papel: 'item inicial', noCatalogo: false, busca: 'A' },
        ],
        divergem: [],
        feitico: { nome: 'Flash ou Purify', confianca: 'baixa',
          nota: 'Só a primeira busca deu feitiço, e deu DOIS sem dizer quando usar cada um. Fica como está: dois nomes, sem critério.' },
        arcana: {
          leitura: '10 Red Moon · 10 Eagle Eye · 10 Reaver',
          confianca: 'baixa',
          nota: 'Só a primeira busca deu arcana. Uma busca só não é cruzamento — por isso a confiança é baixa, mesmo o dado parecendo redondo.',
        },
      },

      "agudo": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/agudo/", "https://hokbuild.com/hero/agudo/", "https://zathong.com/honor-of-kings-agudo/"],
        itens: ["Eternity Blade", "Shadow Ripper", "Daybreaker"],
        arcana: "10 Fate · 3 Longevity + 7 Hunter · 10 Vacuity",
      },
      "alessio": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/alessio/", "https://hokbuild.com/hero/alessio/", "https://zathong.com/honor-of-kings-alessio/"],
        itens: ["Boots of Dexterity", "Shadow Ripper", "Eternity Blade", "Doomsday"],
        extras: ["Daybreaker's Virtue", "Overlord's Might"],
        feitico: "Flash",
        arcana: "10 Dominator · 10 Eagle Eye · 10 Reaver",
      },
      "allain": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/allain/", "https://hokbuild.com/hero/allain/", "https://zathong.com/honor-of-kings-allain/"],
        itens: ["Boots of Fortitude", "Storm Sword", "Blazing Cape", "Blood Rage"],
        extras: ["Dragon's Rage", "Sparkforged Dagger"],
        arcana: "10 Red Moon · 7 Harmony + 3 Hunter · 10 Vacuity",
      },
      "angela": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/angela/", "https://hokbuild.com/hero/angela/", "https://zathong.com/honor-of-kings-angela/"],
        itens: ["Spell Tome", "Boots of Deftness", "Venomous Staff", "Savant's Wrath"],
        extras: ["Void Staff", "Insatiable Tome"],
      },
      "annette": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/annette/", "https://hokbuild.com/hero/annette/", "https://zathong.com/honor-of-kings-annette/"],
        itens: ["Crimson Shadow - Redemption", "Boots of Tranquility"],
        arcana: "10 Compassion",
      },
      "aoyin": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/aoyin/", "https://hokbuild.com/hero/aoyin/", "https://zathong.com/honor-of-kings-aoyin/"],
        itens: ["Lightfoot Shoes", "Eternity Blade", "Boots of Dexterity"],
        arcanaNota: "A busca listou opções soltas (Calamity, Concealment, Eagle Eye) sem fechar a trinca.",
      },
      "arke": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/arke/", "https://hokbuild.com/hero/arke/", "https://zathong.com/honor-of-kings-arke/"],
        itens: ["Relentless Blade", "Boots of Tranquility", "Axe of Torment", "Rapacious Bite"],
        extras: ["Boots of Deftness", "Eternity Blade"],
        arcana: "10 Dominator · 10 Hunter · 10 Eagle Eye",
      },
      "arli": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/arli/", "https://hokbuild.com/hero/arli/", "https://zathong.com/honor-of-kings-arli/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Doomsday", "Sunchaser"],
        extras: ["Eternity Blade", "Daybreaker's Virtue"],
      },
      "arthur": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/arthur/", "https://hokbuild.com/hero/arthur/", "https://zathong.com/honor-of-kings-arthur/"],
        itens: ["Lightfoot Shoes", "Boots of Fortitude", "Blazing Cape", "Glacial Buckler"],
        extras: ["Overlord's Platemail", "Eye of the Phoenix"],
      },
      "ata": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/ata/", "https://hokbuild.com/hero/ata/", "https://zathong.com/honor-of-kings-ata/"],
        itens: ["Boots of Tranquility", "Dragon's Rage", "Blazing Cape", "Eye of the Phoenix"],
        extras: ["Overlord's Platemail", "Ominous Premonition"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "athena": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/athena/", "https://hokbuild.com/hero/athena/", "https://zathong.com/honor-of-kings-athena/"],
        itens: ["Axe of Torment", "Boots of Dexterity", "Dragon's Rage", "Overlord's Might"],
        extras: ["Frostscar's Embrace", "Starbreaker"],
      },
      "augran": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/augran/", "https://hokbuild.com/hero/augran/", "https://zathong.com/honor-of-kings-augran/"],
        arcana: "10 Cataclysm · 10 Hunter · 10 Eagle Eye",
        nota: "A busca devolveu uma rota de habilidades (Path of Passing → Death’s Precipice → Conductor of Souls), não uma lista de itens. Rota de habilidade não é build — o campo de itens ficou vazio.",
      },
      "bai-qi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/bai-qi/", "https://hokbuild.com/hero/bai-qi/", "https://zathong.com/honor-of-kings-bai-qi/"],
        itens: ["Boots of Fortitude", "Blazing Cape", "Cuirass of Savagery", "Eye of the Phoenix"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "biron": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/biron/", "https://hokbuild.com/hero/biron/", "https://zathong.com/honor-of-kings-biron/"],
        itens: ["Meteor", "Boots of Fortitude", "Nettle Gauntlet", "Pure Sky"],
        extras: ["Glacial Buckler", "Boots of Resistance"],
        arcana: "10 Mutation · 2 Concealment + 8 Hunter · 10 Eagle Eye",
      },
      "butterfly": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/butterfly/", "https://hokbuild.com/hero/butterfly/", "https://zathong.com/honor-of-kings-butterfly/"],
        itens: ["Relentless Blade", "Lightfoot Shoes", "Rapacious Bite", "Boots of Dexterity"],
        extras: ["Boots of Resistance", "Axe of Torment"],
        arcana: "10 Mutation · 10 Hunter · 10 Eagle Eye",
      },
      "cai-yan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/cai-yan/", "https://hokbuild.com/hero/cai-yan/", "https://zathong.com/honor-of-kings-cai-yan/"],
        itens: ["Boots of Tranquility", "Holy Grail", "Augur's Word", "Venomous Staff"],
        inicio: "Sage's Codex",
        arcana: "10 Fate · 10 Vacuity · 10 Harmony",
      },
      "chano": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/chano/", "https://hokbuild.com/hero/chano/", "https://zathong.com/honor-of-kings-chano/"],
        itens: ["Boots of Dexterity", "Shadow Ripper", "Eternity Blade"],
        extras: ["Boots of Resistance", "Daybreaker's Virtue", "Bloodweeper"],
      },
      "charlotte": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/charlotte/", "https://hokbuild.com/hero/charlotte/", "https://zathong.com/honor-of-kings-charlotte/"],
        itens: ["Meteor", "Boots of Tranquility", "Frostscar's Embrace", "Axe of Torment"],
        extras: ["Dragon's Rage", "Pure Sky"],
        arcana: "10 Mutation · 9 Harmony + 1 Hunter · 10 Eagle Eye",
      },
      "chicha": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/chicha/", "https://hokbuild.com/hero/chicha/", "https://zathong.com/honor-of-kings-chicha/"],
        itens: ["Axe of Torment", "Shadow Ripper", "Eternity Blade"],
        arcana: "10 Mutation · 10 Hunter · 10 Eagle Eye",
      },
      "cirrus": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/cirrus/", "https://hokbuild.com/hero/cirrus/", "https://zathong.com/honor-of-kings-cirrus/"],
        itens: ["Axe of Torment", "Shadow Ripper", "Eternity Blade"],
        arcana: "10 Red Moon · 6 Reaver + 4 Hunter · 10 Eagle Eye",
      },
      "consort-yu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/consort-yu/", "https://hokbuild.com/hero/consort-yu/", "https://zathong.com/honor-of-kings-consort-yu/"],
        itens: ["Boots of Dexterity", "Eternity Blade", "Twinblades of Destruction", "Shadow Ripper"],
        extras: ["Bloodsoul", "Mortal Punisher"],
        arcana: "10 Red Moon · 10 Eagle Eye · 10 Reaver",
      },
      "daji": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/daji/", "https://hokbuild.com/hero/daji/", "https://zathong.com/honor-of-kings-daji/"],
        itens: ["Spell Tome", "Boots of the Arcane", "Scepter of Reverberation"],
        extras: ["Savant's Wrath", "Void Staff"],
      },
      "da-qiao": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/da-qiao/", "https://hokbuild.com/hero/da-qiao/", "https://zathong.com/honor-of-kings-da-qiao/"],
        itens: ["Guardian", "Guardian - Redemption", "Lightfoot Shoes", "Boots of Deftness"],
        extras: ["Holy Grail", "Clandestine Cape"],
        arcana: "10 Nightmare · 10 Harmony · 10 Mind's Eye",
      },
      "devara": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/devara/", "https://hokbuild.com/hero/devara/", "https://zathong.com/honor-of-kings-devara/"],
        itens: ["Dagger", "Boots of Dexterity", "Sparkforged Dagger", "Tempest", "Doomsday"],
        extras: ["Dragon's Rage", "Blood Rage", "Destiny", "Pure Sky", "Sage's Sanctuary"],
      },
      "dharma": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dharma/", "https://hokbuild.com/hero/dharma/", "https://zathong.com/honor-of-kings-dharma/"],
        itens: ["Boots of Fortitude", "Dragon's Rage", "Frostscar's Embrace", "Axe of Torment"],
        extras: ["Sky Dome"],
        arcana: "10 Mutation · 10 Concealment · 10 Eagle Eye",
      },
      "di-renjie": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/di-renjie/", "https://hokbuild.com/hero/di-renjie/", "https://zathong.com/honor-of-kings-di-renjie/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Doomsday"],
      },
      "dian-wei": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dian-wei/", "https://hokbuild.com/hero/dian-wei/", "https://zathong.com/honor-of-kings-dian-wei/"],
        itens: ["Relentless Blade", "Boots of Tranquility", "Axe of Torment", "Rapacious Bite"],
        extras: ["Spikemail", "Demonsbane"],
      },
      "diaochan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/diaochan/", "https://hokbuild.com/hero/diaochan/", "https://zathong.com/honor-of-kings-diaochan/"],
        itens: ["Boots of Tranquility", "Insatiable Tome", "Savant's Wrath", "Blazing Cape"],
        feitico: "Flash",
        arcana: "Harmony · Compassion · Nightmare",
      },
      "dolia": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dolia/", "https://hokbuild.com/hero/dolia/", "https://zathong.com/honor-of-kings-dolia/"],
        itens: ["Knowledge Gem", "Boots of the Arcane", "Crimson Shadow - Starspring"],
        extras: ["Boots of Resistance", "Frosthold Targe", "Dawnlight", "Venomous Staff", "Sage's Sanctuary"],
        arcana: "10 Fate · 10 Vacuity · 10 Harmony",
      },
      "donghuang": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/donghuang/", "https://hokbuild.com/hero/donghuang/", "https://zathong.com/honor-of-kings-donghuang/"],
        itens: ["Boots of Resistance", "Augur's Word", "Insatiable Tome", "Overlord's Platemail"],
        extras: ["Breakthrough Robe", "Savant's Wrath", "Eye of the Phoenix"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "dr-bian": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dr-bian/", "https://hokbuild.com/hero/dr-bian/", "https://zathong.com/honor-of-kings-dr-bian/"],
        itens: ["Boots of the Arcane", "Holy Grail", "Eye of the Phoenix"],
        extras: ["Scepter of Reverberation", "Savant's Wrath", "Insatiable Tome"],
        arcana: "10 Saint · 10 Tribute · 10 Avarice",
      },
      "dun": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dun/", "https://hokbuild.com/hero/dun/", "https://zathong.com/honor-of-kings-dun/"],
        itens: ["Boots of Fortitude", "Blazing Cape", "Dragon's Rage", "Eye of the Phoenix"],
        extras: ["Blood Rage", "Spikemail"],
        arcana: "10 Fate · 10 Hunter · 10 Vacuity",
      },
      "dyadia": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/dyadia/", "https://hokbuild.com/hero/dyadia/", "https://zathong.com/honor-of-kings-dyadia/"],
        itens: ["Crimson Shadow - Redemption", "Boots of Resistance", "Holy Grail", "Venomous Staff"],
        extras: ["Blazing Cape", "Sage's Sanctuary"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "erin": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/erin/", "https://hokbuild.com/hero/erin/", "https://zathong.com/honor-of-kings-erin/"],
        itens: ["Boots of the Arcane", "Shadow Ripper", "Eternity Blade"],
      },
      "fang": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/fang/", "https://hokbuild.com/hero/fang/", "https://zathong.com/honor-of-kings-fang/"],
        itens: ["Eternity Blade", "Siege Breaker", "Shadow Ripper"],
        arcana: "7 Mutation + 3 Red Moon · 10 Eagle Eye · 7 Reaver + 3 Hunter",
      },
      "fatih": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/fatih/", "https://hokbuild.com/hero/fatih/", "https://zathong.com/honor-of-kings-fatih/"],
        itens: ["Axe of Torment", "Eternity Blade", "Master Sword"],
        arcana: "5 Dominator + 5 Cataclysm · 10 Hunter · 5 Beast Scar + 5 Eagle Eye",
      },
      "feyd": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/feyd/", "https://hokbuild.com/hero/feyd/", "https://zathong.com/honor-of-kings-feyd/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Meteor", "Axe of Torment"],
        extras: ["Frostscar's Embrace", "Rapacious Bite"],
        arcana: "9 Mutation + 1 Red Moon · 10 Concealment · 10 Eagle Eye",
      },
      "florentino": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/florentino/", "https://hokbuild.com/hero/florentino/", "https://zathong.com/honor-of-kings-florentino/"],
        itens: ["Axe of Torment", "Sky Dome", "Eye of the Phoenix"],
        arcana: "10 Fate · 10 Concealment · 10 Vacuity",
      },
      "flowborn-mage": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/flowborn-mage/", "https://hokbuild.com/hero/flowborn-mage/", "https://zathong.com/honor-of-kings-flowborn-mage/"],
        itens: ["Boots of the Arcane", "Sage's Tome", "Frozen Breath", "Blood Clan's Grimoire"],
        extras: ["Insatiable Tome", "Nebulon Wood"],
      },
      "flowborn-marksman": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/flowborn-marksman/", "https://hokbuild.com/hero/flowborn-marksman/", "https://zathong.com/honor-of-kings-flowborn-marksman/"],
        itens: ["Boots of Resistance", "Eternity Blade", "Shadow Ripper", "Daybreaker's Virtue"],
        extras: ["Sunchaser", "Doomsday", "Bloodweeper"],
        arcana: "10 Cataclysm · 10 Hunter · 10 Eagle Eye",
      },
      "flowborn-tank": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/flowborn-tank/", "https://hokbuild.com/hero/flowborn-tank/", "https://zathong.com/honor-of-kings-flowborn-tank/"],
        itens: ["Giant's Grip", "Boots of Resistance", "Blazing Cape", "Bloodweeper"],
        extras: ["Overlord's Platemail", "Glacial Buckler"],
      },
      "fuzi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/fuzi/", "https://hokbuild.com/hero/fuzi/", "https://zathong.com/honor-of-kings-fuzi/"],
        itens: ["Boots of Dexterity", "Doomsday", "Pure Sky", "Spikemail"],
        inicio: "Thunderclap Brand",
        arcana: "10 Conflict · 10 Eagle Eye · 10 Hunter",
      },
      "gan-e-mo": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/gan-e-mo/", "https://hokbuild.com/hero/gan-e-mo/", "https://zathong.com/honor-of-kings-gan-e-mo/"],
        itens: ["Frozen Breath", "Scepter of Reverberation", "Mask of Agony"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "gao": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/gao/", "https://hokbuild.com/hero/gao/", "https://zathong.com/honor-of-kings-gao/"],
        itens: ["Boots of Resistance", "Insatiable Tome", "Savant's Wrath", "Void Staff"],
        extras: ["Splendor"],
        inicio: "Blood Clan's Grimoire",
        feitico: "Flash",
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "gao-changgong": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/gao-changgong/", "https://hokbuild.com/hero/gao-changgong/", "https://zathong.com/honor-of-kings-gao-changgong/"],
        itens: ["Relentless Blade", "Boots of Resistance", "Overlord's Might", "Rapacious Bite"],
        extras: ["Master Sword", "Pure Sky"],
      },
      "garo": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/garo/", "https://hokbuild.com/hero/garo/", "https://zathong.com/honor-of-kings-garo/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Doomsday", "Shadow Ripper"],
        extras: ["Eternity Blade", "Haste - Sunpool"],
        arcana: "10 Dominator · 10 Eagle Eye · 5 Reaver + 5 Hunter",
      },
      "garuda": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/garuda/", "https://hokbuild.com/hero/garuda/", "https://zathong.com/honor-of-kings-garuda/"],
        itens: ["Frozen Breath", "Mask of Agony", "Void Staff"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "guan-yu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/guan-yu/", "https://hokbuild.com/hero/guan-yu/", "https://zathong.com/honor-of-kings-guan-yu/"],
        itens: ["Boots of Fortitude", "Axe of Torment", "Dragon's Rage", "Overlord's Might"],
        extras: ["Glacial Buckler", "Master Sword"],
        inicio: "Meteor",
        arcana: "10 Fate · 10 Harmony · 10 Eagle Eye",
      },
      "guiguzi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/guiguzi/", "https://hokbuild.com/hero/guiguzi/", "https://zathong.com/honor-of-kings-guiguzi/"],
        itens: ["Knowledge Gem", "Boots of Deftness", "Crimson Shadow - Radiance"],
        extras: ["Glacial Buckler", "Succubus Cloak", "Ominous Premonition"],
        arcana: "10 Fate · 10 Vacuity · 10 Harmony",
      },
      "han-xin": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/han-xin/", "https://hokbuild.com/hero/han-xin/", "https://zathong.com/honor-of-kings-han-xin/"],
        itens: ["Axe of Torment", "Cuirass of Savagery", "Master Sword"],
        arcana: "10 Cataclysm · 10 Reaver · 10 Eagle Eye",
      },
      "heino": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/heino/", "https://hokbuild.com/hero/heino/", "https://zathong.com/honor-of-kings-heino/"],
        itens: ["Boots of Tranquility", "Insatiable Tome", "Breakthrough Robe"],
      },
      "hou-yi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/hou-yi/", "https://hokbuild.com/hero/hou-yi/", "https://zathong.com/honor-of-kings-hou-yi/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Eternity Blade"],
        extras: ["Shadow Ripper", "Bloodweeper", "Daybreaker", "Twilight Bow"],
      },
      "huang-zhong": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/huang-zhong/", "https://hokbuild.com/hero/huang-zhong/", "https://zathong.com/honor-of-kings-huang-zhong/"],
        itens: ["Sparkforged Dagger", "Eternity Blade", "Daybreaker"],
        arcana: "5 Red Moon + 5 Dominator · 10 Eagle Eye · 10 Hunter",
      },
      "kaizer": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/kaizer/", "https://hokbuild.com/hero/kaizer/", "https://zathong.com/honor-of-kings-kaizer/"],
        itens: ["Blazing Cape", "Ominous Premonition", "Blood Rage"],
        arcana: "10 Cataclysm · 10 Hunter · 10 Eagle Eye",
      },
      "kongming": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/kongming/", "https://hokbuild.com/hero/kongming/", "https://zathong.com/honor-of-kings-kongming/"],
        itens: ["Boots of the Arcane", "Insatiable Tome", "Ardent Dominion"],
        extras: ["Sage's Tome", "Savant's Wrath", "Void Staff"],
      },
      "kui": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/kui/", "https://hokbuild.com/hero/kui/", "https://zathong.com/honor-of-kings-kui/"],
        itens: ["Knowledge Gem", "Boots of Tranquility", "Crimson Shadow"],
      },
      "lady-sun": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lady-sun/", "https://hokbuild.com/hero/lady-sun/", "https://zathong.com/honor-of-kings-lady-sun/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Eternity Blade", "Master Sword"],
      },
      "lady-zhen": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lady-zhen/", "https://hokbuild.com/hero/lady-zhen/", "https://zathong.com/honor-of-kings-lady-zhen/"],
        itens: ["Scepter of Reverberation", "Boots of the Arcane", "Sage's Tome"],
        arcana: "10 Nightmare · 10 Hunter · 10 Compassion",
      },
      "lam": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lam/", "https://hokbuild.com/hero/lam/", "https://zathong.com/honor-of-kings-lam/"],
        itens: ["Axe of Torment", "Sky Dome", "Cuirass of Savagery"],
        arcana: "10 Mutation · 10 Concealment · 10 Eagle Eye",
      },
      "lapulapu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lapulapu/", "https://hokbuild.com/hero/lapulapu/", "https://zathong.com/honor-of-kings-lapulapu/"],
        itens: ["Protector's Cuirass", "Cloth Jerkin", "Clandestine Cape", "Succubus Cloak", "Overlord's Platemail"],
        feitico: "Flash",
        arcanaNota: "A busca descreveu a arcana como \"estilo tanque Fate/Harmony/Void\" sem dar os números.",
      },
      "li-bai": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/li-bai/", "https://hokbuild.com/hero/li-bai/", "https://zathong.com/honor-of-kings-li-bai/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Rapacious Bite", "Axe of Torment"],
        extras: ["Bloodweeper", "Tempest"],
        arcana: "7 Mutation + 3 Red Moon · 10 Hunter · 10 Eagle Eye",
      },
      "li-xin": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/li-xin/", "https://hokbuild.com/hero/li-xin/", "https://zathong.com/honor-of-kings-li-xin/"],
        itens: ["Axe of Torment", "Spikemail", "Siege Breaker"],
        arcana: "10 Conflict · 10 Eagle Eye · 10 Hunter",
      },
      "lian-po": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lian-po/", "https://hokbuild.com/hero/lian-po/", "https://zathong.com/honor-of-kings-lian-po/"],
        itens: ["Boots of Fortitude", "Spikemail"],
        extras: ["Sky Dome"],
        nota: "A busca deu pouca coisa: só a bota inicial e a troca de Spikemail por Sky Dome contra assassino de explosão, vista em jogo profissional.",
      },
      "liang": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/liang/", "https://hokbuild.com/hero/liang/", "https://zathong.com/honor-of-kings-liang/"],
        itens: ["Scepter of Reverberation", "Savant's Wrath", "Mask of Agony"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "liu-bang": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/liu-bang/", "https://hokbuild.com/hero/liu-bang/", "https://zathong.com/honor-of-kings-liu-bang/"],
        itens: ["Boots of Resistance", "Spikemail", "Blazing Cape", "Eye of the Phoenix"],
        inicio: "Nettle Gauntlet + Cloth Jerkin",
        arcana: "10 Fate · 10 Harmony · 10 Reverberation",
      },
      "liu-bei": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/liu-bei/", "https://hokbuild.com/hero/liu-bei/", "https://zathong.com/honor-of-kings-liu-bei/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Vampiric Scythe", "Axe of Torment", "Rapacious Bite", "Doomsday"],
        arcana: "5 Red Moon + 3 Conflict + 2 Mutation · 10 Hunter · 10 Eagle Eye",
      },
      "liu-shan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/liu-shan/", "https://hokbuild.com/hero/liu-shan/", "https://zathong.com/honor-of-kings-liu-shan/"],
        itens: ["Knowledge Gem", "Boots of Resistance", "Crimson Shadow"],
      },
      "loong": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/loong/", "https://hokbuild.com/hero/loong/", "https://zathong.com/honor-of-kings-loong/"],
        itens: ["Boots of Tranquility", "Axe of Torment", "Eternity Blade"],
      },
      "lorion": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lorion/", "https://hokbuild.com/hero/lorion/", "https://zathong.com/honor-of-kings-lorion/"],
        itens: ["Boots of the Arcane", "Venomous Staff", "Savant's Wrath", "Insatiable Tome"],
        inicio: "Grand Staff + Spell Tome",
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "lu-bu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/lu-bu/", "https://hokbuild.com/hero/lu-bu/", "https://zathong.com/honor-of-kings-lu-bu/"],
        itens: ["Boots of Fortitude", "Spikemail", "Siege Breaker", "Cuirass of Savagery"],
        extras: ["Succubus Cloak", "Blood Rage"],
        feitico: "Flash",
        arcana: "10 Fate · 10 Harmony · 10 Eagle Eye",
      },
      "luara": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/luara/", "https://hokbuild.com/hero/luara/", "https://zathong.com/honor-of-kings-luara/"],
        itens: ["Boots of Fortitude", "Shadow Ripper", "Eternity Blade", "Bloodweeper"],
        inicio: "Twinblades of Destruction",
        arcana: "10 Cataclysm · 5 Reaver + 5 Hunter · 10 Eagle Eye",
      },
      "luban-no7": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/luban-no7/", "https://hokbuild.com/hero/luban-no7/", "https://zathong.com/honor-of-kings-luban-no7/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Eternity Blade", "Cloud Piercing Bow", "Doomsday"],
        extras: ["Sage's Sanctuary"],
        feitico: "Flash",
        arcana: "10 Red Moon · 10 Eagle Eye · 10 Reaver",
      },
      "mai-shiranui": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/mai-shiranui/", "https://hokbuild.com/hero/mai-shiranui/", "https://zathong.com/honor-of-kings-mai-shiranui/"],
        itens: ["Boots of Resistance", "Scepter of Reverberation", "Savant's Wrath", "Insatiable Tome"],
        feitico: "Flash",
        arcana: "10 Nightmare · 10 Reincarnation · 10 Mind's Eye",
      },
      "mayene": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/mayene/", "https://hokbuild.com/hero/mayene/", "https://zathong.com/honor-of-kings-mayene/"],
        itens: ["Boots of Tranquility", "Axe of Torment", "Pure Sky", "Overlord's Might"],
        extras: ["Cuirass of Savagery", "Demonsbane"],
        arcana: "9 Mutation + 1 Red Moon · 10 Concealment · 10 Eagle Eye",
      },
      "menki": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/menki/", "https://hokbuild.com/hero/menki/", "https://zathong.com/honor-of-kings-menki/"],
        itens: ["Boots of Tranquility", "Axe of Torment", "Sparkforged Dagger"],
        arcana: "10 Fate · 10 Hunter · 10 Vacuity",
      },
      "milady": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/milady/", "https://hokbuild.com/hero/milady/", "https://zathong.com/honor-of-kings-milady/"],
        itens: ["Mask of Agony", "Void Staff", "Twilight Stream"],
        feitico: "Flash",
        arcana: "10 Nightmare · 10 Reincarnation · 10 Mind's Eye",
      },
      "ming": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/ming/", "https://hokbuild.com/hero/ming/", "https://zathong.com/honor-of-kings-ming/"],
        itens: ["Crimson Shadow - Redemption", "Frigid Charge", "Savant's Wrath", "Sage's Tome"],
        extras: ["Ominous Premonition", "Succubus Cloak"],
        arcana: "5 Fate · 5 Hunter · 5 Vacuity",
      },
      "mi-yue": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/mi-yue/", "https://hokbuild.com/hero/mi-yue/", "https://zathong.com/honor-of-kings-mi-yue/"],
        itens: ["Boots of Dexterity", "Sparkforged Dagger", "Golden Blade", "Blood Clan's Grimoire"],
        extras: ["Insatiable Tome", "Twilight Stream"],
      },
      "mozi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/mozi/", "https://hokbuild.com/hero/mozi/", "https://zathong.com/honor-of-kings-mozi/"],
        itens: ["Boots of Tranquility", "Holy Grail", "Stone of Sorcery", "Scepter of Reverberation"],
        extras: ["Savant's Wrath", "Nebulon Wood"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "mulan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/mulan/", "https://hokbuild.com/hero/mulan/", "https://zathong.com/honor-of-kings-mulan/"],
        itens: ["Boots of Fortitude", "Axe of Torment", "Starbreaker", "Cuirass of Savagery"],
        inicio: "Sunglow Striker",
        arcana: "10 Mutation · 10 Eagle Eye · 10 Concealment",
      },
      "musashi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/musashi/", "https://hokbuild.com/hero/musashi/", "https://zathong.com/honor-of-kings-musashi/"],
        itens: ["Relentless Blade", "Boots of Tranquility", "Axe of Torment", "Rapacious Bite"],
        extras: ["Blazing Cape", "Blood Rage"],
        arcana: "8 Mutation + 2 Red Moon · 10 Concealment · 10 Eagle Eye",
      },
      "nakoruru": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/nakoruru/", "https://hokbuild.com/hero/nakoruru/", "https://zathong.com/honor-of-kings-nakoruru/"],
        itens: ["Rapacious Bite", "Boots of Tranquility", "Axe of Torment", "Mortal Punisher"],
        extras: ["Overlord's Might", "Spikemail"],
        arcana: "10 Mutation · 10 Concealment · 10 Eagle Eye",
      },
      "nezha": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/nezha/", "https://hokbuild.com/hero/nezha/", "https://zathong.com/honor-of-kings-nezha/"],
        itens: ["Frostscar's Embrace", "Cuirass of Savagery", "Blazing Cape"],
        feitico: "Execute",
        arcana: "10 Fate · 5 Harmony + 5 Concealment · 10 Vacuity",
        nota: "Lembrando que o KIT deste herói está com conflito total registrado nas habilidades — duas leituras que não batem. A build é de outra busca e não resolve aquilo.",
      },
      "nuwa": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/nuwa/", "https://hokbuild.com/hero/nuwa/", "https://zathong.com/honor-of-kings-nuwa/"],
        itens: ["Boots of the Arcane", "Scepter of Reverberation", "Savant's Wrath", "Insatiable Tome"],
        inicio: "Stone of Sorcery",
        arcana: "10 Nightmare · 10 Hunter · 10 Tribute",
      },
      "pei": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/pei/", "https://hokbuild.com/hero/pei/", "https://zathong.com/honor-of-kings-pei/"],
        itens: ["Rapacious Bite", "Axe of Torment", "Master Sword"],
        feitico: "Smite",
        arcana: "10 Conflict · 10 Eagle Eye · 10 Hunter",
      },
      "sakeer": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/sakeer/", "https://hokbuild.com/hero/sakeer/", "https://zathong.com/honor-of-kings-sakeer/"],
        itens: ["Crimson Shadow - Radiance", "Overlord's Platemail", "Breakthrough Robe"],
        arcana: "10 Longevity · 10 Vacuity · 10 Fate",
      },
      "shangguan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/shangguan/", "https://hokbuild.com/hero/shangguan/", "https://zathong.com/honor-of-kings-shangguan/"],
        itens: ["Spell Tome", "Boots of the Arcane", "Venomous Staff", "Savant's Wrath"],
        extras: ["Sage's Tome", "Boots of Resistance"],
        feitico: "Flash",
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "shi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/shi/", "https://hokbuild.com/hero/shi/", "https://zathong.com/honor-of-kings-shi/"],
        itens: ["Scepter of Reverberation", "Savant's Wrath", "Insatiable Tome"],
        arcana: "10 Nightmare · 7 Hunter + 3 Reincarnation · 10 Mind's Eye",
      },
      "shouyue": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/shouyue/", "https://hokbuild.com/hero/shouyue/", "https://zathong.com/honor-of-kings-shouyue/"],
        itens: ["Sparkforged Dagger", "Boots of Dexterity", "Doomsday", "Shadow Ripper"],
        extras: ["Overlord's Might", "Eternity Blade"],
        arcana: "10 Cataclysm · 10 Eagle Eye · 10 Hunter",
      },
      "sima-yi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/sima-yi/", "https://hokbuild.com/hero/sima-yi/", "https://zathong.com/honor-of-kings-sima-yi/"],
        itens: ["Guerrilla Machete", "Blood Clan's Grimoire", "Boots of Dexterity", "Insatiable Tome"],
        extras: ["Breakthrough Robe", "Runeblade"],
        feitico: "Smite",
        arcana: "5 Fate + 5 Nightmare · 10 Mind's Eye · 10 Hunter",
      },
      "sun-bin": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/sun-bin/", "https://hokbuild.com/hero/sun-bin/", "https://zathong.com/honor-of-kings-sun-bin/"],
        itens: ["Knowledge Gem", "Boots of the Arcane", "Crimson Shadow"],
        extras: ["Glacial Buckler", "Succubus Cloak", "Ominous Premonition"],
        arcana: "10 Nightmare · 10 Mind's Eye · 10 Reincarnation",
      },
      "sun-ce": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/sun-ce/", "https://hokbuild.com/hero/sun-ce/", "https://zathong.com/honor-of-kings-sun-ce/"],
        itens: ["Meteor", "Boots of Fortitude", "Axe of Torment", "Frigid Charge"],
        extras: ["Succubus Cloak", "Spikemail"],
        feitico: "Smite",
        arcana: "2 Red Moon + 8 Mutation · 9 Hunter + 1 Harmony · 10 Eagle Eye",
      },
      "sun-wukong": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/sun-wukong/", "https://hokbuild.com/hero/sun-wukong/", "https://zathong.com/honor-of-kings-sun-wukong/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Eternity Blade", "Shadow Ripper"],
        extras: ["Rapacious Bite", "Master Sword"],
        nota: "ATENÇÃO: a sua lista tem DOIS heróis com nome parecido — \"Sun Wukong\" e \"Wukong\". A busca respondeu por \"Wukong\" sem dizer qual. Esta build ficou no Sun Wukong porque foi o nome pesquisado, mas a ambiguidade está aqui escrita em vez de escondida.",
      },
      "ukyo-tachibana": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/ukyo-tachibana/", "https://hokbuild.com/hero/ukyo-tachibana/", "https://zathong.com/honor-of-kings-ukyo-tachibana/"],
        itens: ["Boots of Dexterity", "Pure Sky", "Axe of Torment", "Spikemail"],
        inicio: "Thunderclap Brand",
        arcana: "10 Cataclysm · 10 Eagle Eye · 10 Reaver",
      },
      "umbrosa": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/umbrosa/", "https://hokbuild.com/hero/umbrosa/", "https://zathong.com/honor-of-kings-umbrosa/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Meteor", "Axe of Torment"],
        extras: ["Nettle Gauntlet", "Rapacious Bite"],
        arcana: "10 Mutation · 10 Hunter · 10 Eagle Eye",
      },
      "wang-zhaojun": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/wang-zhaojun/", "https://hokbuild.com/hero/wang-zhaojun/", "https://zathong.com/honor-of-kings-wang-zhaojun/"],
        itens: ["Guardian - Radiance", "Boots of Fortitude", "Glacial Buckler"],
        nota: "A busca devolveu uma build de DEFESA para uma maga de meio — pode estar descrevendo outra função ou outro herói. Guardado como veio, com este aviso.",
      },
      "wukong": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/wukong/", "https://hokbuild.com/hero/wukong/", "https://zathong.com/honor-of-kings-wukong/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Eternity Blade", "Shadow Ripper"],
        extras: ["Rapacious Bite", "Master Sword", "Bloodweeper"],
        arcana: "10 Dominator · 10 Eagle Eye · 10 Reaver",
        nota: "ATENÇÃO: a sua lista tem \"Wukong\" E \"Sun Wukong\" como heróis separados. As buscas pelos dois nomes devolveram builds quase iguais (Relentless Blade, Boots of Dexterity, Eternity Blade, Shadow Ripper) — o que pode significar que as fontes tratam os dois como o mesmo herói, ou que um dos resumos respondeu pelo outro. Não juntei os dois nem escolhi um: cada um ficou com o que a busca do próprio nome devolveu, e o aviso está aqui. Uma das buscas listou \"Nightmare\" entre os itens, que é nome de arcana — o resumo misturou as listas ali.",
      },
      "wuyan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/wuyan/", "https://hokbuild.com/hero/wuyan/", "https://zathong.com/honor-of-kings-wuyan/"],
        itens: ["Lightfoot Shoes", "Blazing Cape", "Storm Sword"],
        extras: ["Axe of Torment", "Glacial Buckler"],
        arcanaNota: "A busca deu \"Stealth x4, Harmony x6, Eagle Eye e Fate\" — quatro arcanas para três espaços, e sem fechar os números. Ficou como veio.",
      },
      "xiang-yu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/xiang-yu/", "https://hokbuild.com/hero/xiang-yu/", "https://zathong.com/honor-of-kings-xiang-yu/"],
        itens: ["Boots of Resistance", "Blazing Cape", "Succubus Cloak"],
        extras: ["Eye of the Phoenix", "Spikemail"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "xiao-qiao": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/xiao-qiao/", "https://hokbuild.com/hero/xiao-qiao/", "https://zathong.com/honor-of-kings-xiao-qiao/"],
        itens: ["Boots of the Arcane", "Stone of Sorcery", "Scepter of Reverberation"],
        extras: ["Savant's Wrath", "Insatiable Tome"],
        arcana: "10 Nightmare · 10 Reincarnation · 10 Mind's Eye",
      },
      "xuance": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/xuance/", "https://hokbuild.com/hero/xuance/", "https://zathong.com/honor-of-kings-xuance/"],
        itens: ["Relentless Blade", "Boots of Dexterity", "Axe of Torment", "Doomsday"],
        extras: ["Thunderclap Brand", "Eternity Blade"],
        arcana: "10 Red Moon · 8 Reaver + 2 Hunter · 10 Eagle Eye",
      },
      "yang-jian": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yang-jian/", "https://hokbuild.com/hero/yang-jian/", "https://zathong.com/honor-of-kings-yang-jian/"],
        itens: ["Relentless Blade", "Boots of Tranquility", "Dragon's Rage", "Rapacious Bite"],
        extras: ["Eye of the Phoenix", "Blood Rage"],
        arcana: "10 Mutation · 10 Hunter · 10 Eagle Eye",
      },
      "yango": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yango/", "https://hokbuild.com/hero/yango/", "https://zathong.com/honor-of-kings-yango/"],
        itens: ["Storm Sword", "Meteor", "Boots of Tranquility"],
      },
      "yao": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yao/", "https://hokbuild.com/hero/yao/", "https://zathong.com/honor-of-kings-yao/"],
        itens: ["Boots of Resistance", "Axe of Torment", "Spikemail", "Siege Breaker"],
        inicio: "Hunting Knife",
        arcana: "10 Mutation · 10 Concealment · 10 Eagle Eye",
      },
      "yaria": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yaria/", "https://hokbuild.com/hero/yaria/", "https://zathong.com/honor-of-kings-yaria/"],
        itens: ["Knowledge Gem", "Boots of Tranquility", "Crimson Shadow - Radiance"],
        extras: ["Overlord's Platemail", "Longnight Guardian", "Blazing Cape"],
        arcana: "10 Fate · 10 Vacuity · 10 Harmony",
      },
      "ying": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/ying/", "https://hokbuild.com/hero/ying/", "https://zathong.com/honor-of-kings-ying/"],
        itens: ["Siege Breaker", "Axe of Torment", "Frostscar's Embrace"],
        arcana: "10 Cataclysm · 5 Concealment + 5 Eagle Eye · 10 Reaver",
      },
      "yixing": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yixing/", "https://hokbuild.com/hero/yixing/", "https://zathong.com/honor-of-kings-yixing/"],
        itens: ["Boots of the Arcane", "Stone of Sorcery", "Frozen Breath"],
        extras: ["Mask of Agony", "Scepter of Reverberation", "Tome of Wisdom"],
        arcana: "10 Nightmare · 10 Hunter · 10 Compassion",
      },
      "yuhuan": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/yuhuan/", "https://hokbuild.com/hero/yuhuan/", "https://zathong.com/honor-of-kings-yuhuan/"],
        itens: ["Scepter of Reverberation", "Stave of Sorcery", "Tome of Wisdom"],
        arcana: "10 Nightmare · 10 Hunter · 10 Mind's Eye",
      },
      "zhang-fei": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/zhang-fei/", "https://hokbuild.com/hero/zhang-fei/", "https://zathong.com/honor-of-kings-zhang-fei/"],
        itens: ["Knowledge Gem", "Guardian", "Guardian - Redemption", "Lightfoot Shoes"],
        extras: ["Boots of Tranquility", "Frigid Charge"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "zhang-liang": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/zhang-liang/", "https://hokbuild.com/hero/zhang-liang/", "https://zathong.com/honor-of-kings-zhang-liang/"],
        itens: ["Boots of Tranquility", "Scepter of Reverberation", "Savant's Wrath", "Moon Soul"],
        extras: ["Void Staff", "Tome of Wisdom"],
        arcanaNota: "A busca deu os nomes (Nightmare, Hunter, Mind's Eye) sem os números.",
      },
      "zhao-yun": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/zhao-yun/", "https://hokbuild.com/hero/zhao-yun/", "https://zathong.com/honor-of-kings-zhao-yun/"],
        itens: ["Rapacious Bite", "Boots of Resistance", "Frostscar's Grip", "Longnight Guardian"],
        extras: ["Sage's Sanctuary"],
        feitico: "Smite",
        arcanaNota: "A busca deu os nomes (Mutation, Eagle Eye, Hunter) sem os números.",
        nota: "A busca chamou este herói de \"Zilong\" e o classificou como tier C. Também listou \"Nightmare\" entre os ITENS, que é nome de arcana — sinal de que o resumo misturou as duas listas. Por isso a confiança aqui é baixa. Lembrando que o kit deste herói já tem três leituras que brigam entre si (ver o alerta nas habilidades).",
      },
      "zhuangzi": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/zhuangzi/", "https://hokbuild.com/hero/zhuangzi/", "https://zathong.com/honor-of-kings-zhuangzi/"],
        itens: ["Glacial Buckler", "Ominous Premonition", "Longnight Guardian"],
        arcana: "10 Fate · 10 Harmony · 10 Vacuity",
      },
      "ziya": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/ziya/", "https://hokbuild.com/hero/ziya/", "https://zathong.com/honor-of-kings-ziya/"],
        itens: ["Stone of Sorcery", "Boots of Resistance", "Scepter of Reverberation", "Sage's Tome"],
        extras: ["Ominous Premonition", "Void Staff"],
      },
      "zhou-yu": {
        cruzado: false,
        buscas: 1,
        urls: ["https://hokstats.gg/heroes/zhou-yu/", "https://hokbuild.com/hero/zhou-yu/", "https://zathong.com/honor-of-kings-zhou-yu/"],
        itens: ["Boots of the Arcane", "Venomous Staff", "Sage's Tome"],
      },

    },
  };

})(window.U);
