/**
 * Comida: enlatados, secos, perecíveis (carne, peixe, laticínios, verduras),
 * frutas, doces, congelados e refeições prontas.
 * Fome/sede em pontos (0–100); estragar em dias de jogo.
 */
import type { FoodProps } from '../ItemTypes';
import { category, type ItemEntry } from './define';

type Extra = Partial<ItemEntry>;

const can = (id: string, name: string, body: string, label: string, food: Omit<FoodProps, 'thirst'> & { thirst?: number }, desc: string, extra: Extra = {}): ItemEntry => ({
  id,
  name,
  sub: 'enlatado',
  kg: 0.42,
  vol: 0.4,
  stack: 6,
  icon: { f: 'can', c: body, c2: label },
  desc,
  tags: ['enlatado', 'lata'],
  food: { thirst: 0, needs: 'abridor', ...food },
  ...extra,
});

const dry = (id: string, name: string, sub: string, kg: number, icon: ItemEntry['icon'], food: FoodProps, desc: string, extra: Extra = {}): ItemEntry => ({
  id,
  name,
  sub,
  kg,
  stack: 5,
  icon,
  desc,
  food,
  ...extra,
});

const fresh = (id: string, name: string, sub: string, kg: number, icon: ItemEntry['icon'], food: FoodProps, desc: string, extra: Extra = {}): ItemEntry => ({
  id,
  name,
  sub,
  kg,
  stack: 6,
  cond: 'perishable',
  icon,
  desc,
  food,
  ...extra,
});

const fruit = (id: string, name: string, color: string, shape: string, kcal: number, hunger: number, thirst: number, spoil: readonly [number, number, number], desc: string, extra: Extra = {}): ItemEntry => ({
  id,
  name,
  sub: 'fruta',
  kg: 0.18,
  stack: 10,
  cond: 'perishable',
  icon: { f: 'fruit', c: color, k: shape },
  desc,
  tags: ['fruta', 'natural'],
  food: { kcal, hunger, thirst, spoil },
  ...extra,
});

export const FOOD = category('comida', { stack: 6, cond: 'none', tags: ['comida'] }, [
  // ---------------- enlatados (não estragam fechados; precisam de abridor ou faca)
  can('feijao', 'Lata de feijão', '#9aa0a6', '#7a4a2a', { kcal: 400, hunger: 25 }, 'Precisa de abridor ou de uma faca.'),
  can('milhoLata', 'Lata de milho', '#9aa0a6', '#e6c23a', { kcal: 250, hunger: 15 }, 'Milho verde em conserva.'),
  can('ervilhaLata', 'Lata de ervilha', '#9aa0a6', '#6e9a3c', { kcal: 220, hunger: 14 }, 'Ervilhas em conserva.'),
  can('sardinha', 'Sardinha em lata', '#b8bcc0', '#3f6f9a', { kcal: 280, hunger: 18, thirst: -4, needs: undefined }, 'Tampa de abrir com o dedo.', { kg: 0.14, vol: 0.15, stack: 10, icon: { f: 'can', c: '#b8bcc0', c2: '#3f6f9a', k: 'flat' } }),
  can('atum', 'Atum em lata', '#b8bcc0', '#c24a3a', { kcal: 300, hunger: 20, thirst: -3, needs: undefined }, 'Tampa de abrir com o dedo.', { kg: 0.18, vol: 0.18, stack: 10, icon: { f: 'can', c: '#b8bcc0', c2: '#c24a3a', k: 'flat' } }),
  can('salsichaLata', 'Salsicha em lata', '#9aa0a6', '#c8703a', { kcal: 450, hunger: 22, thirst: -4 }, 'Salsichas em salmoura.'),
  can('apresuntado', 'Apresuntado', '#9aa0a6', '#d88a8a', { kcal: 600, hunger: 30, thirst: -5 }, 'Carne em conserva. Salgada.', { rar: 'incomum' }),
  can('sopaLata', 'Sopa em lata', '#9aa0a6', '#c89a3a', { kcal: 250, hunger: 18, thirst: 8 }, 'Melhor quente, mas serve fria.'),
  can('feijoadaLata', 'Feijoada em lata', '#9aa0a6', '#3a2a22', { kcal: 700, hunger: 38, thirst: -6 }, 'Pesada e salvadora.', { rar: 'incomum', kg: 0.85, vol: 0.8, icon: { f: 'can', c: '#9aa0a6', c2: '#3a2a22', big: true } }),
  can('pessegoCalda', 'Pêssego em calda', '#9aa0a6', '#f0a24a', { kcal: 350, hunger: 12, thirst: 10 }, 'Doce e com caldo.', { rar: 'incomum' }),
  can('leiteCondensado', 'Leite condensado', '#d8d4c8', '#3a6fb0', { kcal: 1300, hunger: 20, thirst: -8 }, 'Pura energia. Dá sede.', { rar: 'incomum' }),
  can('extratoTomate', 'Extrato de tomate', '#b8bcc0', '#c8342a', { kcal: 120, hunger: 4, thirst: -1 }, 'Ingrediente, não refeição.', { kg: 0.14, vol: 0.14, tags: ['ingrediente'] }),
  can('racaoCao', 'Ração de cachorro (lata)', '#9aa0a6', '#8a5a2a', { kcal: 500, hunger: 20, thirst: -4 }, 'Se a fome apertar...', { rar: 'incomum' }),
  // ---------------- secos e mercearia
  dry('arroz', 'Arroz (1 kg)', 'grao', 1, { f: 'bag', c: '#f2eee2', c2: '#3a8a4a', big: true }, { kcal: 3600, hunger: 0, thirst: 0 }, 'Cru. Precisa cozinhar com água.', { tags: ['ingrediente', 'cozinhar'] }),
  dry('feijaoCru', 'Feijão (1 kg)', 'grao', 1, { f: 'bag', c: '#6a3a2a', c2: '#e0c060', big: true }, { kcal: 3300, hunger: 0, thirst: 0 }, 'Cru. Horas de panela.', { tags: ['ingrediente', 'cozinhar'] }),
  dry('macarrao', 'Macarrão (500 g)', 'massa', 0.5, { f: 'bag', c: '#f0d27a', c2: '#2a5aa0' }, { kcal: 1750, hunger: 0, thirst: 0 }, 'Cru. Precisa de água fervendo.', { tags: ['ingrediente', 'cozinhar'] }),
  dry('miojo', 'Macarrão instantâneo', 'massa', 0.09, { f: 'bag', c: '#e8b43a', c2: '#c8342a' }, { kcal: 380, hunger: 14, thirst: -6 }, 'Dá para comer cru, quebradinho.', { stack: 10 }),
  dry('farinhaTrigo', 'Farinha de trigo (1 kg)', 'ingrediente', 1, { f: 'bag', c: '#f4f1ea', c2: '#c8a24a', big: true }, { kcal: 3600, hunger: 2, thirst: -5 }, 'Base de pão e massa.', { tags: ['ingrediente'] }),
  dry('farinhaMandioca', 'Farinha de mandioca', 'ingrediente', 1, { f: 'bag', c: '#efe0b0', c2: '#8a6a2a', big: true }, { kcal: 3500, hunger: 10, thirst: -8 }, 'Farofa sem mais nada.', { tags: ['ingrediente'] }),
  dry('fuba', 'Fubá (1 kg)', 'ingrediente', 1, { f: 'bag', c: '#f2c84a', c2: '#c8342a', big: true }, { kcal: 3600, hunger: 2, thirst: -5 }, 'Polenta, angu, bolo.', { tags: ['ingrediente'] }),
  dry('acucar', 'Açúcar (1 kg)', 'ingrediente', 1, { f: 'bag', c: '#f7f7f2', c2: '#3a6fb0', big: true }, { kcal: 3870, hunger: 3, thirst: -4 }, 'Energia rápida.', { cond: 'battery', tags: ['ingrediente', 'acucar'] }),
  dry('sal', 'Sal (1 kg)', 'ingrediente', 1, { f: 'bag', c: '#f7f7f2', c2: '#c8342a', big: true }, { kcal: 0, hunger: 0, thirst: -20 }, 'Conserva carne. Não se come puro.', { cond: 'battery', tags: ['ingrediente', 'sal'] }),
  dry('cafePo', 'Café em pó', 'ingrediente', 0.5, { f: 'bag', c: '#3a2418', c2: '#c8a24a' }, { kcal: 10, hunger: 0, thirst: 0 }, 'Precisa de água quente. Rende umas vinte canecas.', { cond: 'battery', tags: ['ingrediente', 'cafe'] }),
  dry('oleoSoja', 'Óleo de soja', 'ingrediente', 0.95, { f: 'bottle', c: '#e8c84a', c2: '#e8c84a', k: 'oil' }, { kcal: 8000, hunger: 2, thirst: -2 }, 'Para fritar. Também queima.', { cond: 'battery', tags: ['ingrediente', 'oleo', 'combustivel'] }),
  dry('azeite', 'Azeite', 'ingrediente', 0.55, { f: 'bottle', c: '#8a9a2a', c2: '#2a4a2a', k: 'glass' }, { kcal: 4400, hunger: 2, thirst: -2 }, 'Garrafa de vidro escuro.', { rar: 'incomum', cond: 'battery', tags: ['ingrediente', 'oleo'] }),
  dry('mel', 'Mel', 'doce', 0.5, { f: 'jar', c: '#e8a42a', c2: '#c8a24a' }, { kcal: 1500, hunger: 10, thirst: -3 }, 'Não estraga nunca.', { rar: 'incomum', tags: ['doce'] }),
  dry('geleia', 'Geleia', 'doce', 0.35, { f: 'jar', c: '#a8324a', c2: '#e0e0d0' }, { kcal: 900, hunger: 8, thirst: -2 }, 'Pote de vidro.', { tags: ['doce'] }),
  dry('pastaAmendoim', 'Pasta de amendoim', 'doce', 0.5, { f: 'jar', c: '#b8763a', c2: '#c8342a' }, { kcal: 2900, hunger: 25, thirst: -8 }, 'Muitas calorias por grama.', { rar: 'incomum' }),
  dry('achocolatado', 'Achocolatado em pó', 'ingrediente', 0.4, { f: 'can', c: '#5a3a24', c2: '#e8c84a' }, { kcal: 1600, hunger: 5, thirst: -4 }, 'Com leite fica melhor.', { tags: ['doce'] }),
  dry('leitePo', 'Leite em pó', 'ingrediente', 0.4, { f: 'can', c: '#f2eee2', c2: '#3a6fb0' }, { kcal: 2000, hunger: 12, thirst: -8 }, 'Misture com água limpa.', { rar: 'incomum', tags: ['ingrediente'] }),
  dry('biscoito', 'Pacote de biscoito', 'doce', 0.2, { f: 'bag', c: '#d9922e', c2: '#f3dfa9' }, { kcal: 900, hunger: 10, thirst: -4 }, 'Seco e salgado.', { stack: 6 }),
  dry('bolachaAgua', 'Bolacha de água e sal', 'doce', 0.2, { f: 'bag', c: '#f2e6c0', c2: '#2a5aa0' }, { kcal: 850, hunger: 10, thirst: -6 }, 'Resiste a quase tudo.', { stack: 6 }),
  dry('salgadinho', 'Salgadinho', 'lanche', 0.1, { f: 'bag', c: '#e8762a', c2: '#e8c84a' }, { kcal: 500, hunger: 6, thirst: -6 }, 'Mais ar que salgadinho.', { stack: 8 }),
  dry('chocolate', 'Barra de chocolate', 'doce', 0.1, { f: 'bar', c: '#4a2a1a', c2: '#c8342a' }, { kcal: 540, hunger: 7, thirst: -2 }, 'Ânimo em forma de barra.', { stack: 10, rar: 'incomum', tags: ['doce'] }),
  dry('barraCereal', 'Barra de cereal', 'lanche', 0.03, { f: 'bar', c: '#c8a24a', c2: '#3a8a4a' }, { kcal: 110, hunger: 4, thirst: -1 }, 'Leve para carregar.', { stack: 12 }),
  dry('balas', 'Pacote de balas', 'doce', 0.1, { f: 'bag', c: '#e84a8a', c2: '#f2f2f2' }, { kcal: 380, hunger: 3, thirst: -2 }, 'Açúcar colorido.', { stack: 8, tags: ['doce'] }),
  dry('cereal', 'Caixa de cereal', 'lanche', 0.3, { f: 'box', c: '#e8c84a', c2: '#c8342a' }, { kcal: 1100, hunger: 12, thirst: -4 }, 'Crocante mesmo sem leite.', { stack: 4 }),
  dry('aveia', 'Aveia em flocos', 'grao', 0.25, { f: 'box', c: '#e8d8a0', c2: '#3a8a4a' }, { kcal: 950, hunger: 10, thirst: -5 }, 'Mingau com água.', { stack: 4 }),
  dry('amendoim', 'Amendoim torrado', 'lanche', 0.15, { f: 'bag', c: '#c8342a', c2: '#e8c84a' }, { kcal: 880, hunger: 9, thirst: -6 }, 'Salgado.', { stack: 8 }),
  dry('pipocaMicro', 'Pipoca de micro-ondas', 'lanche', 0.1, { f: 'bag', c: '#f2f2f2', c2: '#c8342a' }, { kcal: 450, hunger: 4, thirst: -3 }, 'Sem micro-ondas, só na panela.', { stack: 8, tags: ['cozinhar'] }),
  dry('gelatinaPo', 'Gelatina em pó', 'doce', 0.03, { f: 'box', c: '#c8342a', c2: '#f2f2f2' }, { kcal: 110, hunger: 1, thirst: -1 }, 'Precisa de água quente e geladeira.', { stack: 12, tags: ['ingrediente'] }),
  dry('farofaPronta', 'Farofa pronta', 'lanche', 0.25, { f: 'bag', c: '#e8c84a', c2: '#8a4a2a' }, { kcal: 1000, hunger: 12, thirst: -9 }, 'Seca demais para comer sozinha.', { stack: 6 }),
  dry('racaoMilitar', 'Ração de campanha', 'refeicao', 0.6, { f: 'bag', c: '#5a6a3a', c2: '#2a2a1a', big: true }, { kcal: 1250, hunger: 45, thirst: -3 }, 'Refeição completa, embalada para durar anos.', { rar: 'muito-raro', stack: 3 }),
  // ---------------- perecíveis: carnes, peixes, laticínios, padaria
  fresh('carneBovina', 'Carne bovina', 'carne', 0.5, { f: 'meat', c: '#b83a3a', c2: '#f2e2d2' }, { kcal: 1250, hunger: 30, thirst: -4, spoil: [1, 2, 4], raw: true }, 'Crua. Cozinhe antes de comer.', { tags: ['carne', 'cozinhar'] }),
  fresh('frango', 'Frango', 'carne', 0.6, { f: 'meat', c: '#e8b8a0', c2: '#f2e8d8', k: 'bone' }, { kcal: 1100, hunger: 28, thirst: -3, spoil: [1, 2, 3], raw: true }, 'Cru dá intoxicação.', { tags: ['carne', 'cozinhar'] }),
  fresh('linguica', 'Linguiça', 'carne', 0.4, { f: 'meat', c: '#a84a3a', k: 'sausage' }, { kcal: 1200, hunger: 24, thirst: -6, spoil: [2, 4, 7], raw: true }, 'Defumada, mas crua.', { tags: ['carne', 'cozinhar'] }),
  fresh('peixe', 'Peixe', 'peixe', 0.7, { f: 'fish', c: '#8aa0b0' }, { kcal: 700, hunger: 24, thirst: -2, spoil: [1, 2, 3], raw: true }, 'Fresco hoje. Amanhã, nem tanto.', { stack: 3, tags: ['peixe', 'cozinhar'] }),
  fresh('ovos', 'Ovos', 'ovo', 0.06, { f: 'egg', c: '#f2e6d0' }, { kcal: 75, hunger: 5, thirst: 0, spoil: [10, 20, 30], raw: true }, 'Crus, só em emergência.', { stack: 12, tags: ['ovo', 'cozinhar', 'ingrediente'] }),
  fresh('queijo', 'Queijo', 'laticinio', 0.4, { f: 'cheese', c: '#f0c84a' }, { kcal: 1400, hunger: 20, thirst: -6, spoil: [5, 10, 16] }, 'Mussarela em peça.', { stack: 4, tags: ['laticinio'] }),
  fresh('presunto', 'Presunto fatiado', 'frios', 0.2, { f: 'meat', c: '#e8a0a0', k: 'slices' }, { kcal: 300, hunger: 10, thirst: -4, spoil: [2, 4, 6] }, 'Frios da geladeira.', { tags: ['frios'] }),
  fresh('leiteFresco', 'Leite (garrafa)', 'laticinio', 1.05, { f: 'bottle', c: '#f4f4f0', c2: '#3a6fb0', k: 'milk' }, { kcal: 600, hunger: 8, thirst: 25, spoil: [2, 4, 6] }, 'Sem geladeira, dura pouco.', { stack: 2, tags: ['laticinio'] }),
  fresh('iogurte', 'Iogurte', 'laticinio', 0.17, { f: 'cup', c: '#f2f2f2', c2: '#e84a8a' }, { kcal: 150, hunger: 5, thirst: 4, spoil: [4, 8, 14] }, 'Potinho de morango.', { stack: 6, tags: ['laticinio'] }),
  fresh('manteiga', 'Manteiga', 'laticinio', 0.2, { f: 'box', c: '#f2d26a', c2: '#2a5aa0' }, { kcal: 1400, hunger: 4, thirst: -2, spoil: [10, 20, 40] }, 'Ingrediente.', { tags: ['ingrediente'] }),
  fresh('paoFrances', 'Pão francês', 'padaria', 0.05, { f: 'bread', c: '#d8983a', k: 'roll' }, { kcal: 135, hunger: 6, thirst: -2, spoil: [1, 3, 6] }, 'Duro no segundo dia.', { stack: 10, tags: ['pao'] }),
  fresh('paoForma', 'Pão de forma', 'padaria', 0.5, { f: 'bread', c: '#e8b870', k: 'loaf' }, { kcal: 1250, hunger: 22, thirst: -5, spoil: [4, 8, 12] }, 'Mofa em uma semana.', { stack: 2, tags: ['pao'] }),
  fresh('bolo', 'Bolo caseiro', 'padaria', 0.6, { f: 'bread', c: '#a8683a', k: 'cake' }, { kcal: 2200, hunger: 30, thirst: -5, spoil: [2, 5, 8] }, 'Alguém fez antes de tudo acontecer.', { stack: 1, rar: 'incomum', tags: ['doce'] }),
  fresh('sanduiche', 'Sanduíche', 'refeicao', 0.2, { f: 'bread', c: '#e8b870', k: 'sandwich' }, { kcal: 450, hunger: 15, thirst: -3, spoil: [1, 2, 3] }, 'Embrulhado em papel filme.', { stack: 3 }),
  fresh('marmita', 'Marmita congelada', 'refeicao', 0.45, { f: 'box', c: '#e8e8e0', c2: '#c8342a', k: 'tray' }, { kcal: 600, hunger: 30, thirst: -3, spoil: [1, 2, 4] }, 'Sem freezer, descongelou.', { stack: 3 }),
  fresh('pizzaCongelada', 'Pizza congelada', 'refeicao', 0.46, { f: 'box', c: '#c8342a', c2: '#e8c84a', k: 'pizza' }, { kcal: 1100, hunger: 35, thirst: -6, spoil: [1, 3, 5], raw: true }, 'Precisa de forno.', { stack: 2, tags: ['cozinhar'] }),
  fresh('lasanhaCongelada', 'Lasanha congelada', 'refeicao', 0.6, { f: 'box', c: '#e8762a', c2: '#3a6a2a', k: 'tray' }, { kcal: 900, hunger: 36, thirst: -5, spoil: [1, 3, 5], raw: true }, 'Precisa de forno.', { stack: 2, tags: ['cozinhar'] }),
  // ---------------- verduras e legumes
  fresh('alface', 'Alface', 'verdura', 0.25, { f: 'veg', c: '#7ac84a', k: 'leaf' }, { kcal: 40, hunger: 3, thirst: 5, spoil: [2, 4, 6] }, 'Murcha rápido.', { tags: ['verdura', 'natural'] }),
  fresh('tomate', 'Tomate', 'verdura', 0.15, { f: 'fruit', c: '#d8342a', k: 'round' }, { kcal: 25, hunger: 3, thirst: 5, spoil: [4, 7, 10] }, 'Vermelho e maduro.', { stack: 10, tags: ['verdura', 'natural'] }),
  fresh('cebola', 'Cebola', 'verdura', 0.15, { f: 'fruit', c: '#c89a5a', k: 'onion' }, { kcal: 40, hunger: 2, thirst: 1, spoil: [20, 40, 60] }, 'Dura bastante.', { stack: 10, tags: ['verdura', 'ingrediente'] }),
  fresh('alho', 'Alho', 'verdura', 0.05, { f: 'fruit', c: '#f0e8d8', k: 'onion' }, { kcal: 5, hunger: 0, thirst: 0, spoil: [30, 60, 90] }, 'Tempero.', { stack: 20, tags: ['ingrediente'] }),
  fresh('batata', 'Batata', 'verdura', 0.2, { f: 'fruit', c: '#c8a06a', k: 'potato' }, { kcal: 150, hunger: 6, thirst: 0, spoil: [20, 40, 60], raw: true }, 'Crua não presta. Cozida, sim.', { stack: 10, tags: ['verdura', 'cozinhar'] }),
  fresh('cenoura', 'Cenoura', 'verdura', 0.1, { f: 'veg', c: '#e8762a', k: 'carrot' }, { kcal: 40, hunger: 3, thirst: 2, spoil: [10, 20, 30] }, 'Crocante.', { stack: 10, tags: ['verdura', 'natural'] }),
  fresh('abobrinha', 'Abobrinha', 'verdura', 0.3, { f: 'veg', c: '#5a8a3a', k: 'long' }, { kcal: 50, hunger: 4, thirst: 4, spoil: [5, 9, 14] }, 'Melhor cozida.', { stack: 6, tags: ['verdura'] }),
  fresh('repolho', 'Repolho', 'verdura', 0.9, { f: 'veg', c: '#a8d88a', k: 'cabbage' }, { kcal: 220, hunger: 10, thirst: 8, spoil: [10, 20, 30] }, 'Pesado e durável.', { stack: 2, tags: ['verdura'] }),
  fresh('mandioca', 'Mandioca', 'verdura', 0.5, { f: 'veg', c: '#8a5a3a', k: 'root' }, { kcal: 800, hunger: 16, thirst: 0, spoil: [4, 8, 12], raw: true }, 'Precisa cozinhar.', { stack: 4, tags: ['verdura', 'cozinhar'] }),
  // ---------------- frutas (árvores do mapa e mercados)
  fruit('maca', 'Maçã', '#c8342a', 'apple', 80, 5, 4, [8, 15, 22], 'Colhida do pé ou da fruteira.'),
  fruit('laranja', 'Laranja', '#f0922a', 'round', 60, 4, 8, [8, 14, 20], 'Suculenta.'),
  fruit('manga', 'Manga', '#e8b83a', 'mango', 150, 8, 7, [3, 6, 9], 'Madura e cheirosa.', { kg: 0.35 }),
  fruit('limao', 'Limão', '#8ac83a', 'lemon', 20, 1, 3, [10, 18, 25], 'Azedo. Bom com água.'),
  fruit('goiaba', 'Goiaba', '#b8c85a', 'round', 70, 5, 4, [3, 5, 8], 'Por dentro, vermelha.'),
  fruit('banana', 'Banana', '#f0d24a', 'banana', 105, 7, 1, [3, 6, 8], 'Escurece rápido.', { kg: 0.12 }),
  fruit('abacate', 'Abacate', '#4a6a2a', 'avocado', 320, 14, 1, [4, 7, 10], 'Gordura boa.', { kg: 0.4, rar: 'incomum' }),
  fruit('amora', 'Amoras', '#4a1a3a', 'berries', 40, 2, 2, [1, 3, 5], 'Um punhado da amoreira.', { kg: 0.08, stack: 12 }),
  fruit('jabuticaba', 'Jabuticabas', '#2a1a2a', 'berries', 50, 3, 3, [2, 4, 6], 'Um punhado, direto do tronco.', { kg: 0.1, stack: 12, rar: 'incomum' }),
  fruit('pitanga', 'Pitangas', '#d8342a', 'berries', 30, 2, 3, [2, 4, 6], 'Pequenas e azedinhas.', { kg: 0.06, stack: 12 }),
]);
