/**
 * Eletrônicos, agricultura e natureza, itens domésticos, leitura e valor.
 */
import { category, type ItemEntry } from './define';

const it = (id: string, name: string, sub: string, kg: number, icon: ItemEntry['icon'], desc: string, extra: Partial<ItemEntry> = {}): ItemEntry => ({
  id,
  name,
  sub,
  kg,
  icon,
  desc,
  ...extra,
});

export const ELECTRONICS = category('eletronico', { stack: 1, cond: 'durable', tags: ['eletronico'] }, [
  it('pilhas', 'Pilhas', 'energia', 0.03, { f: 'battery', c: '#2a2c30', c2: '#d98b2b' }, 'Tamanho AA.', { stack: 12, cond: 'battery', power: { hours: 8 }, tags: ['pilha', 'energia'] }),
  it('bateria9v', 'Bateria 9 V', 'energia', 0.05, { f: 'battery', c: '#2a2a2a', c2: '#e8c84a', k: '9v' }, 'Para rádio e detector.', { stack: 6, cond: 'battery', power: { hours: 6 }, rar: 'incomum', tags: ['pilha', 'energia'] }),
  it('bateriaFerramenta', 'Bateria de ferramenta', 'energia', 0.6, { f: 'battery', c: '#e8c84a', c2: '#2a2a2a', k: 'pack' }, 'Encaixa na furadeira.', { stack: 2, cond: 'battery', power: { hours: 1 }, rar: 'raro', tags: ['bateria-ferramenta', 'energia'] }),
  it('bateriaCarro', 'Bateria de carro', 'energia', 14, { f: 'battery', c: '#2a2a2a', c2: '#c8342a', k: 'car', big: true }, 'Pesada. Liga rádio e luz por dias.', { cond: 'battery', power: { hours: 60 }, rar: 'incomum', tags: ['bateria-carro', 'energia'] }),
  it('powerbank', 'Carregador portátil', 'energia', 0.25, { f: 'device', k: 'powerbank', c: '#3a3a42' }, 'Carrega aparelho pequeno.', { cond: 'battery', power: { hours: 10 }, rar: 'incomum', tags: ['energia'] }),
  it('lanterna', 'Lanterna', 'luz', 0.35, { f: 'device', k: 'flashlight', c: '#2c2f33' }, 'Precisa de pilhas.', { cond: 'device', power: { hours: 6, needs: 'pilha' }, tags: ['luz'] }),
  it('lanternaCabeca', 'Lanterna de cabeça', 'luz', 0.15, { f: 'device', k: 'headlamp', c: '#2a2a2a' }, 'Mãos livres, luz na frente. Vista na cabeça e ligue.', { cond: 'device', power: { hours: 8, needs: 'pilha' }, rar: 'raro', tags: ['luz'], wear: { slot: 'cabeca', insulation: 0.02, bite: 0, scratch: 0.02 } }),
  it('radio', 'Rádio portátil', 'comunicacao', 0.8, { f: 'device', k: 'radio', c: '#3a3a3a' }, 'Talvez alguém ainda transmita.', { cond: 'device', power: { hours: 20, needs: 'pilha' }, rar: 'incomum', tags: ['radio'] }),
  it('radioComunicador', 'Rádio comunicador', 'comunicacao', 0.3, { f: 'device', k: 'walkie', c: '#2a2a2a' }, 'Walkie-talkie.', { cond: 'device', power: { hours: 12, needs: 'pilha' }, rar: 'raro', tags: ['radio'] }),
  it('celular', 'Celular', 'comunicacao', 0.2, { f: 'device', k: 'phone', c: '#1a1a1a' }, 'Sem sinal. Mostra a hora e a lanterna ainda funciona.', { cond: 'device', power: { hours: 5 }, tags: ['luz'] }),
  it('carregadorCelular', 'Carregador de celular', 'cabo', 0.1, { f: 'coil', k: 'cable', c: '#f2f2f2' }, 'Cabo e fonte.', { stack: 3, cond: 'none', tags: ['fio'] }),
  it('fioEletrico', 'Fio elétrico', 'cabo', 0.4, { f: 'coil', k: 'cable', c: '#c8342a' }, 'Dez metros.', { stack: 5, cond: 'none', tags: ['fio', 'eletrica'] }),
  it('extensao', 'Extensão elétrica', 'cabo', 0.8, { f: 'coil', k: 'cable', c: '#f2f2f2' }, 'Leva energia do gerador até a casa.', { stack: 2, rar: 'incomum', tags: ['fio', 'eletrica'] }),
  it('componentes', 'Componentes eletrônicos', 'peca', 0.05, { f: 'board', c: '#2a7a4a' }, 'Resistores, capacitores, chips.', { stack: 20, cond: 'none', rar: 'incomum', tags: ['componentes', 'eletrica'] }),
  it('placaCircuito', 'Placa de circuito', 'peca', 0.1, { f: 'board', c: '#3a6a3a', big: true }, 'Tirada de um aparelho.', { stack: 5, cond: 'none', tags: ['componentes', 'eletrica'] }),
  it('lampada', 'Lâmpada', 'luz', 0.05, { f: 'bulb' }, 'Para quando voltar a energia.', { stack: 6, cond: 'none', tags: ['lampada'] }),
  it('multimetro', 'Multímetro', 'instrumento', 0.3, { f: 'device', k: 'multimeter', c: '#e8c84a' }, 'Mede tensão e continuidade.', { cond: 'device', power: { hours: 40, needs: 'pilha' }, rar: 'raro', tags: ['eletrica'] }),
  it('relogioDigital', 'Relógio digital', 'acessorio', 0.05, { f: 'jewel', k: 'watch', c: '#2a2a2a' }, 'Tem alarme.', { cond: 'device', power: { hours: 2000 }, tags: ['relogio'] }),
  it('gerador', 'Gerador portátil', 'energia', 45, { f: 'device', k: 'generator', c: '#c8342a', big: true }, 'Barulhento. Precisa de gasolina.', { cond: 'durable', rar: 'muito-raro', tags: ['gerador', 'energia'] }),
]);

export const NATURE = category('natureza', { stack: 10, cond: 'none', tags: ['natural'] }, [
  it('sementeTomate', 'Sementes de tomate', 'semente', 0.01, { f: 'seeds', c: '#d8342a' }, 'Colhe em ~60 dias.', { stack: 20, seed: { crop: 'tomate', growDays: 60 }, tags: ['semente', 'agricultura'] }),
  it('sementeAlface', 'Sementes de alface', 'semente', 0.01, { f: 'seeds', c: '#7ac84a' }, 'Colhe em ~40 dias.', { stack: 20, seed: { crop: 'alface', growDays: 40 }, tags: ['semente', 'agricultura'] }),
  it('sementeCenoura', 'Sementes de cenoura', 'semente', 0.01, { f: 'seeds', c: '#e8762a' }, 'Colhe em ~70 dias.', { stack: 20, seed: { crop: 'cenoura', growDays: 70 }, tags: ['semente', 'agricultura'] }),
  it('sementeMilho', 'Sementes de milho', 'semente', 0.02, { f: 'seeds', c: '#e8c83a' }, 'Colhe em ~90 dias.', { stack: 20, seed: { crop: 'milho', growDays: 90 }, tags: ['semente', 'agricultura'] }),
  it('sementeFeijao', 'Sementes de feijão', 'semente', 0.02, { f: 'seeds', c: '#6a3a2a' }, 'Colhe em ~80 dias.', { stack: 20, seed: { crop: 'feijao', growDays: 80 }, tags: ['semente', 'agricultura'] }),
  it('sementeAbobora', 'Sementes de abóbora', 'semente', 0.02, { f: 'seeds', c: '#e8922a' }, 'Colhe em ~100 dias.', { stack: 20, rar: 'incomum', seed: { crop: 'abobora', growDays: 100 }, tags: ['semente', 'agricultura'] }),
  it('ramaMandioca', 'Rama de mandioca', 'muda', 0.3, { f: 'stick', c: '#8a6a4a' }, 'Pedaço de caule para plantar.', { stack: 10, rar: 'incomum', seed: { crop: 'mandioca', growDays: 240 }, tags: ['semente', 'agricultura'] }),
  it('adubo', 'Saco de adubo', 'insumo', 5, { f: 'sack', c: '#5a3a2a', c2: '#3a8a4a' }, 'Terra melhor, colheita maior.', { stack: 1, vol: 6, tags: ['adubo', 'agricultura'] }),
  it('fertilizante', 'Fertilizante NPK', 'insumo', 1, { f: 'sack', c: '#f2f2f2', c2: '#3a6ab0' }, 'Um punhado por canteiro.', { stack: 3, rar: 'incomum', tags: ['adubo', 'agricultura'] }),
  it('regador', 'Regador', 'ferramenta', 0.6, { f: 'bucket', k: 'watering', c: '#3a8a4a' }, 'Rega sem desperdício.', { stack: 1, cond: 'durable', tags: ['regar', 'agricultura', 'recipiente-agua'] }),
  it('galho', 'Galho', 'coleta', 0.5, { f: 'stick', c: '#7a5232' }, 'Lenha fina, cabo de ferramenta, lança.', { tags: ['madeira', 'galho', 'lenha'] }),
  it('pedra', 'Pedra', 'coleta', 0.8, { f: 'stone', c: '#8a8a82' }, 'Martelo improvisado. Arremesso.', { stack: 6, tags: ['pedra'] }),
  it('pedraLasca', 'Lasca de pedra', 'coleta', 0.2, { f: 'stone', c: '#6a6a66', k: 'shard' }, 'Afiada.', { stack: 10, tags: ['pedra', 'afiado'] }),
  it('cogumeloComestivel', 'Cogumelo comestível', 'cogumelo', 0.05, { f: 'mushroom', c: '#c8a07a' }, 'Nasce na sombra úmida.', { stack: 12, cond: 'perishable', food: { kcal: 20, hunger: 2, thirst: 1, spoil: [2, 4, 6] }, tags: ['cogumelo', 'comida'] }),
  it('cogumeloVenenoso', 'Cogumelo de chapéu vermelho', 'cogumelo', 0.05, { f: 'mushroom', c: '#c8342a', c2: 'spots' }, 'Bonito. Bonito demais.', { stack: 12, cond: 'perishable', food: { kcal: 20, hunger: 2, thirst: 0, spoil: [2, 4, 6], toxic: true }, tags: ['cogumelo', 'venenoso'] }),
  it('ervas', 'Ervas (erva-cidreira)', 'erva', 0.03, { f: 'veg', k: 'herb', c: '#6aa84a' }, 'Chá calmante.', { stack: 12, cond: 'perishable', food: { kcal: 2, hunger: 0, thirst: 1, spoil: [3, 6, 9] }, tags: ['erva', 'cha'] }),
  it('capim', 'Capim seco', 'fibra', 0.1, { f: 'veg', k: 'grass', c: '#c8b86a' }, 'Acende fogo, trança corda.', { stack: 20, tags: ['fibra', 'isca-fogo'] }),
  it('minhocas', 'Minhocas', 'isca', 0.02, { f: 'bits', k: 'worms', c: '#c87a7a' }, 'Isca de pesca.', { stack: 20, cond: 'perishable', food: { kcal: 5, hunger: 1, thirst: 0, spoil: [2, 4, 6] }, tags: ['isca'] }),
  it('bambu', 'Bambu', 'coleta', 1, { f: 'stick', c: '#a8b85a', k: 'bamboo' }, 'Leve e resistente.', { stack: 4, rar: 'incomum', tags: ['madeira', 'bambu'] }),
  it('folhas', 'Folhas secas', 'coleta', 0.05, { f: 'veg', k: 'leaves', c: '#b8883a' }, 'Acendem rápido.', { stack: 20, tags: ['isca-fogo'] }),
]);

export const HOUSEHOLD = category('domestico', { stack: 4, cond: 'none', tags: ['domestico'] }, [
  it('panela', 'Panela', 'cozinha', 1.2, { f: 'pot', k: 'pot', c: '#9aa0a6' }, 'Ferve água. Cozinha arroz.', { stack: 1, cond: 'durable', metal: true, tags: ['panela', 'cozinhar', 'ferver', 'recipiente-agua'] }),
  it('chaleira', 'Chaleira', 'cozinha', 0.8, { f: 'pot', k: 'kettle', c: '#c8c8c0' }, 'Ferve água rápido.', { stack: 1, cond: 'durable', metal: true, tags: ['ferver', 'recipiente-agua'] }),
  it('panelaPressao', 'Panela de pressão', 'cozinha', 2.5, { f: 'pot', k: 'pressure', c: '#9aa0a6' }, 'Feijão em meia hora.', { stack: 1, cond: 'durable', metal: true, rar: 'incomum', tags: ['panela', 'cozinhar', 'ferver'] }),
  it('prato', 'Prato', 'cozinha', 0.4, { f: 'dish', k: 'plate', c: '#f2f2f2' }, 'Louça.', { stack: 6 }),
  it('tigela', 'Tigela', 'cozinha', 0.3, { f: 'dish', k: 'bowl', c: '#e8e0d0' }, 'Sopa, mingau.', { stack: 6, tags: ['recipiente-agua'] }),
  it('caneca', 'Caneca', 'cozinha', 0.3, { f: 'dish', k: 'mug', c: '#c8342a' }, 'Café, chá, água.', { stack: 6, tags: ['recipiente-agua'] }),
  it('copo', 'Copo', 'cozinha', 0.2, { f: 'dish', k: 'cup', c: '#bfe0e8' }, 'De vidro.', { stack: 6, tags: ['vidro'] }),
  it('garfo', 'Garfo', 'talher', 0.05, { f: 'cutlery', k: 'fork' }, 'Talher.', { stack: 12, metal: true }),
  it('colher', 'Colher', 'talher', 0.05, { f: 'cutlery', k: 'spoon' }, 'Talher.', { stack: 12, metal: true }),
  it('conchaCozinha', 'Concha', 'talher', 0.15, { f: 'cutlery', k: 'ladle' }, 'Serve sopa.', { stack: 2, metal: true }),
  it('garrafaTermica', 'Garrafa térmica', 'cozinha', 0.6, { f: 'bottle', c: '#c8342a', c2: '#2a2a2a', k: 'thermos' }, 'Mantém quente (ou frio).', { stack: 1, rar: 'incomum', tags: ['recipiente-agua'] }),
  it('detergente', 'Detergente', 'limpeza', 0.5, { f: 'bottle', c: '#e8d84a', c2: '#3a8a4a', k: 'pet' }, 'Lava louça e ferida (se não houver outro).', { stack: 3, tags: ['limpeza', 'sabao'] }),
  it('aguaSanitaria', 'Água sanitária', 'limpeza', 1, { f: 'bottle', c: '#f2f2f2', c2: '#3a6ab0', k: 'jug' }, 'Duas gotas por litro tornam a água bebível.', { stack: 2, tags: ['limpeza', 'cloro', 'tratar-agua'] }),
  it('sabaoBarra', 'Sabão em barra', 'limpeza', 0.2, { f: 'bar', c: '#f2e8a0', c2: '#f2e8a0' }, 'Lava roupa e mãos.', { stack: 5, tags: ['limpeza', 'sabao'] }),
  it('sabonete', 'Sabonete', 'higiene', 0.09, { f: 'bar', c: '#e8a0c8', c2: '#e8a0c8' }, 'Cheiroso.', { stack: 6, tags: ['higiene', 'sabao'] }),
  it('shampoo', 'Xampu', 'higiene', 0.35, { f: 'bottle', c: '#3a8ab0', c2: '#f2f2f2', k: 'pet' }, 'Luxo.', { stack: 2, tags: ['higiene'] }),
  it('papelHigienico', 'Papel higiênico', 'higiene', 0.1, { f: 'roll', c: '#f7f7f7', k: 'paper' }, 'Vale ouro.', { stack: 8, tags: ['higiene', 'isca-fogo'] }),
  it('escovaDentes', 'Escova de dentes', 'higiene', 0.02, { f: 'cutlery', k: 'toothbrush', c: '#3a8ab0' }, 'Dentes também sobrevivem.', { stack: 6, tags: ['higiene'] }),
  it('pastaDentes', 'Pasta de dentes', 'higiene', 0.1, { f: 'tube', c: '#f2f2f2', c2: '#c8342a' }, 'Menta.', { stack: 6, tags: ['higiene'] }),
  it('toalha', 'Toalha', 'banho', 0.5, { f: 'towel', c: '#3a8ab0' }, 'Seca, limpa, vira curativo.', { stack: 2, tags: ['tecido-fonte'] }),
  it('lencol', 'Lençol', 'cama', 0.6, { f: 'towel', c: '#e8e0f0', k: 'sheet' }, 'Vira corda, curativo, cortina.', { stack: 2, tags: ['tecido-fonte'] }),
  it('cobertor', 'Cobertor', 'cama', 1.5, { f: 'towel', c: '#8a3a3a', k: 'blanket' }, 'Noite fria, cobertor quente.', { stack: 1, tags: ['tecido-fonte', 'aquecer'] }),
  it('travesseiro', 'Travesseiro', 'cama', 0.6, { f: 'towel', c: '#f2f2f2', k: 'pillow' }, 'Dormir melhor ajuda a sobreviver.', { stack: 1 }),
  it('vela', 'Vela', 'luz', 0.08, { f: 'candle' }, 'Luz fraca que não precisa de pilha. Acenda com isqueiro ou fósforo.', { stack: 10, cond: 'battery', power: { hours: 5 }, tags: ['luz', 'vela'] }),
  it('balde', 'Balde', 'limpeza', 0.8, { f: 'bucket', c: '#3a6ab0' }, 'Junta água de chuva.', { stack: 1, cond: 'durable', tags: ['recipiente-agua', 'balde'] }),
  it('vassoura', 'Vassoura', 'limpeza', 0.8, { f: 'blunt', k: 'broom', c: '#c8a06a' }, 'O cabo vira arma ou lança.', { stack: 1, cond: 'durable', tags: ['cabo'] }),
  it('cadeiraDobravel', 'Cadeira dobrável', 'movel', 3.5, { f: 'chair', c: '#6a6a72' }, 'Desmontada, rende metal.', { stack: 1, vol: 12, cond: 'durable', metal: true, tags: ['movel'] }),
  it('garrafaVazia', 'Garrafa de refrigerante vazia', 'recipiente', 0.05, { f: 'bottle', c: '#d8eef4', c2: '#c8342a', k: 'emptyPet' }, 'Guarda água.', { stack: 6, tags: ['recipiente-agua', 'plastico'] }),
  it('pilhaPratos', 'Tupperware', 'cozinha', 0.2, { f: 'dish', k: 'box', c: '#bfe0e8' }, 'Guarda comida.', { stack: 4 }),
]);

export const READING = category('leitura', { stack: 1, cond: 'durable', tags: ['leitura', 'papel'] }, [
  it('livroRomance', 'Livro de romance', 'livro', 0.5, { f: 'book', c: '#a83a5a' }, 'Passa o tempo. Acalma.', { read: { minutes: 240 } }),
  it('livroSuspense', 'Livro de suspense', 'livro', 0.5, { f: 'book', c: '#2a2a3a' }, 'Irônico, nessas circunstâncias.', { read: { minutes: 240 } }),
  it('livroCarpintaria', 'Manual de carpintaria', 'manual', 0.6, { f: 'book', c: '#b38652', k: 'manual' }, 'Ensina a construir melhor.', { rar: 'raro', read: { minutes: 300, skill: 'carpintaria' } }),
  it('livroMecanica', 'Manual de mecânica', 'manual', 0.6, { f: 'book', c: '#6a6a72', k: 'manual' }, 'Motores, peças, ferramentas.', { rar: 'raro', read: { minutes: 300, skill: 'mecanica' } }),
  it('livroPrimeirosSocorros', 'Guia de primeiros socorros', 'manual', 0.4, { f: 'book', c: '#c8342a', k: 'manual' }, 'Curativos que funcionam.', { rar: 'raro', read: { minutes: 240, skill: 'medicina' } }),
  it('livroAgricultura', 'Manual de horta', 'manual', 0.5, { f: 'book', c: '#3a8a4a', k: 'manual' }, 'Plantar, adubar, colher.', { rar: 'raro', read: { minutes: 240, skill: 'agricultura' } }),
  it('livroEletronica', 'Manual de eletrônica', 'manual', 0.5, { f: 'book', c: '#3a6ab0', k: 'manual' }, 'Circuitos e rádios.', { rar: 'raro', read: { minutes: 300, skill: 'eletronica' } }),
  it('livroCulinaria', 'Livro de receitas', 'manual', 0.7, { f: 'book', c: '#e8922a', k: 'manual' }, 'Comida boa com pouco.', { rar: 'incomum', read: { minutes: 180, skill: 'culinaria' } }),
  it('livroPesca', 'Guia de pesca', 'manual', 0.3, { f: 'book', c: '#3a8ab0', k: 'manual' }, 'Iscas, nós, lugares.', { rar: 'raro', read: { minutes: 180, skill: 'pesca' } }),
  it('revista', 'Revista', 'revista', 0.2, { f: 'book', c: '#e84a8a', k: 'magazine' }, 'Fofocas de um mundo que acabou.', { stack: 4, read: { minutes: 30 }, tags: ['isca-fogo'] }),
  it('revistaArmas', 'Revista de armas', 'revista', 0.2, { f: 'book', c: '#4a5a3a', k: 'magazine' }, 'Manutenção e limpeza de armas.', { stack: 4, rar: 'raro', read: { minutes: 60, skill: 'armas' } }),
  it('gibi', 'Gibi', 'revista', 0.1, { f: 'book', c: '#e8c84a', k: 'magazine' }, 'Distrai.', { stack: 6, read: { minutes: 20 } }),
  it('jornal', 'Jornal', 'revista', 0.2, { f: 'book', c: '#d8d4c8', k: 'newspaper' }, '"SURTO SE ESPALHA" na capa.', { stack: 6, read: { minutes: 15 }, tags: ['isca-fogo'] }),
  it('mapaCidade', 'Mapa da cidade', 'mapa', 0.05, { f: 'book', c: '#e8dcb0', k: 'map' }, 'Ruas, lojas, delegacia, hospital.', { stack: 1, rar: 'incomum', read: { minutes: 5 } }),
  it('mapaAnotado', 'Mapa com anotações', 'mapa', 0.05, { f: 'book', c: '#e8dcb0', k: 'mapmark' }, 'Alguém marcou lugares com caneta vermelha.', { stack: 1, rar: 'raro', read: { minutes: 5 } }),
  it('bilhete', 'Bilhete', 'documento', 0.01, { f: 'book', c: '#f2f2e8', k: 'note' }, '"Fomos para o abrigo do ginásio. Não volte."', { stack: 5, read: { minutes: 1 } }),
  it('diario', 'Diário', 'documento', 0.3, { f: 'book', c: '#5a3a2a' }, 'Os últimos dias de alguém.', { rar: 'incomum', read: { minutes: 60 } }),
  it('documentos', 'Documentos', 'documento', 0.05, { f: 'book', c: '#3a6ab0', k: 'id' }, 'RG, CPF, carteira de trabalho.', { stack: 5 }),
  it('fotografia', 'Fotografia', 'documento', 0.01, { f: 'book', c: '#f2f2f2', k: 'photo' }, 'Uma família sorrindo.', { stack: 5 }),
  it('baralho', 'Baralho', 'jogo', 0.1, { f: 'book', c: '#c8342a', k: 'cards' }, 'Paciência em noite longa.', { stack: 2, read: { minutes: 30 } }),
]);

export const VALUABLES = category('valor', { stack: 5, cond: 'none', rar: 'incomum', tags: ['valor'] }, [
  it('dinheiro', 'Dinheiro', 'dinheiro', 0.001, { f: 'jewel', k: 'money' }, 'Notas de real. Hoje, papel.', { stack: 500, rar: 'comum', value: 0, tags: ['papel', 'isca-fogo'] }),
  it('carteira', 'Carteira', 'pessoal', 0.1, { f: 'jewel', k: 'wallet' }, 'Documentos e umas notas.', { stack: 3, value: 1 }),
  it('anelOuro', 'Anel de ouro', 'joia', 0.01, { f: 'jewel', k: 'ring', c: '#e8c84a' }, 'Pequeno e valioso (para quem ainda liga).', { rar: 'raro', value: 20 }),
  it('alianca', 'Aliança', 'joia', 0.005, { f: 'jewel', k: 'ring', c: '#f0d060' }, 'Tem um nome gravado por dentro.', { rar: 'incomum', value: 15 }),
  it('colar', 'Colar', 'joia', 0.02, { f: 'jewel', k: 'necklace', c: '#e8c84a' }, 'Corrente dourada.', { rar: 'raro', value: 25 }),
  it('relogioPulso', 'Relógio de pulso', 'joia', 0.08, { f: 'jewel', k: 'watch', c: '#c8c8c0' }, 'Ainda funciona. Corda automática.', { rar: 'raro', cond: 'durable', value: 30, tags: ['relogio'] }),
  it('chaveCarro', 'Chave de carro', 'pessoal', 0.03, { f: 'jewel', k: 'carkey' }, 'De algum carro por aí.', { stack: 3, value: 2, tags: ['chave'] }),
  it('chaveCasa', 'Molho de chaves', 'pessoal', 0.05, { f: 'jewel', k: 'key' }, 'De alguma porta por aí.', { stack: 3, value: 1, tags: ['chave'] }),
  it('ouro', 'Barrinha de ouro', 'joia', 0.1, { f: 'jewel', k: 'goldbar', c: '#e8c84a' }, 'Alguém guardava para o fim do mundo.', { rar: 'rarissimo', stack: 5, value: 200 }),
]);
